/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.glean.api_client.glean_api_client.models.components.Event;
import com.glean.api_client.glean_api_client.models.components.Feedback;
import com.glean.api_client.glean_api_client.models.operations.FeedbackResponse;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Exception;
import java.util.List;
import org.junit.jupiter.api.Test;

public class ActivitiesTests {

    @Test
    public void testActivities_Feedback() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("feedback");
        Glean sdk = Glean.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .client(testHttpClient)
                .apiToken("<YOUR_BEARER_TOKEN_HERE>")
            .build();

        FeedbackResponse res = sdk.client().activity().feedback()
                .feedback1(Feedback.builder()
                    .trackingTokens(List.of(
                        "trackingTokens"))
                    .event(Event.VIEW)
                    .build())
                .call();
        assertEquals(200, res.statusCode());
    }
}