/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.glean.api_client.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * BulkIndexDocumentsRequest
 * 
 * <p>Describes the request body of the /bulkindexdocuments API call
 */
public class BulkIndexDocumentsRequest {

    /**
     * Unique id that must be used for this bulk upload instance
     */
    @JsonProperty("uploadId")
    private String uploadId;

    /**
     * true if this is the first page of the upload. Defaults to false
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isFirstPage")
    private Optional<Boolean> isFirstPage;

    /**
     * true if this is the last page of the upload. Defaults to false
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("isLastPage")
    private Optional<Boolean> isLastPage;

    /**
     * Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("forceRestartUpload")
    private Optional<Boolean> forceRestartUpload;

    /**
     * Datasource of the documents
     */
    @JsonProperty("datasource")
    private String datasource;

    /**
     * Batch of documents for the datasource
     */
    @JsonProperty("documents")
    private List<DocumentDefinition> documents;

    /**
     * True if older documents need to be force deleted after the upload completes. Defaults to older documents being deleted asynchronously. This must only be set when `isLastPage = true`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("disableStaleDocumentDeletionCheck")
    private Optional<Boolean> disableStaleDocumentDeletionCheck;

    @JsonCreator
    public BulkIndexDocumentsRequest(
            @JsonProperty("uploadId") String uploadId,
            @JsonProperty("isFirstPage") Optional<Boolean> isFirstPage,
            @JsonProperty("isLastPage") Optional<Boolean> isLastPage,
            @JsonProperty("forceRestartUpload") Optional<Boolean> forceRestartUpload,
            @JsonProperty("datasource") String datasource,
            @JsonProperty("documents") List<DocumentDefinition> documents,
            @JsonProperty("disableStaleDocumentDeletionCheck") Optional<Boolean> disableStaleDocumentDeletionCheck) {
        Utils.checkNotNull(uploadId, "uploadId");
        Utils.checkNotNull(isFirstPage, "isFirstPage");
        Utils.checkNotNull(isLastPage, "isLastPage");
        Utils.checkNotNull(forceRestartUpload, "forceRestartUpload");
        Utils.checkNotNull(datasource, "datasource");
        Utils.checkNotNull(documents, "documents");
        Utils.checkNotNull(disableStaleDocumentDeletionCheck, "disableStaleDocumentDeletionCheck");
        this.uploadId = uploadId;
        this.isFirstPage = isFirstPage;
        this.isLastPage = isLastPage;
        this.forceRestartUpload = forceRestartUpload;
        this.datasource = datasource;
        this.documents = documents;
        this.disableStaleDocumentDeletionCheck = disableStaleDocumentDeletionCheck;
    }
    
    public BulkIndexDocumentsRequest(
            String uploadId,
            String datasource,
            List<DocumentDefinition> documents) {
        this(uploadId, Optional.empty(), Optional.empty(), Optional.empty(), datasource, documents, Optional.empty());
    }

    /**
     * Unique id that must be used for this bulk upload instance
     */
    @JsonIgnore
    public String uploadId() {
        return uploadId;
    }

    /**
     * true if this is the first page of the upload. Defaults to false
     */
    @JsonIgnore
    public Optional<Boolean> isFirstPage() {
        return isFirstPage;
    }

    /**
     * true if this is the last page of the upload. Defaults to false
     */
    @JsonIgnore
    public Optional<Boolean> isLastPage() {
        return isLastPage;
    }

    /**
     * Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
     */
    @JsonIgnore
    public Optional<Boolean> forceRestartUpload() {
        return forceRestartUpload;
    }

    /**
     * Datasource of the documents
     */
    @JsonIgnore
    public String datasource() {
        return datasource;
    }

    /**
     * Batch of documents for the datasource
     */
    @JsonIgnore
    public List<DocumentDefinition> documents() {
        return documents;
    }

    /**
     * True if older documents need to be force deleted after the upload completes. Defaults to older documents being deleted asynchronously. This must only be set when `isLastPage = true`
     */
    @JsonIgnore
    public Optional<Boolean> disableStaleDocumentDeletionCheck() {
        return disableStaleDocumentDeletionCheck;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Unique id that must be used for this bulk upload instance
     */
    public BulkIndexDocumentsRequest withUploadId(String uploadId) {
        Utils.checkNotNull(uploadId, "uploadId");
        this.uploadId = uploadId;
        return this;
    }

    /**
     * true if this is the first page of the upload. Defaults to false
     */
    public BulkIndexDocumentsRequest withIsFirstPage(boolean isFirstPage) {
        Utils.checkNotNull(isFirstPage, "isFirstPage");
        this.isFirstPage = Optional.ofNullable(isFirstPage);
        return this;
    }

    /**
     * true if this is the first page of the upload. Defaults to false
     */
    public BulkIndexDocumentsRequest withIsFirstPage(Optional<Boolean> isFirstPage) {
        Utils.checkNotNull(isFirstPage, "isFirstPage");
        this.isFirstPage = isFirstPage;
        return this;
    }

    /**
     * true if this is the last page of the upload. Defaults to false
     */
    public BulkIndexDocumentsRequest withIsLastPage(boolean isLastPage) {
        Utils.checkNotNull(isLastPage, "isLastPage");
        this.isLastPage = Optional.ofNullable(isLastPage);
        return this;
    }

    /**
     * true if this is the last page of the upload. Defaults to false
     */
    public BulkIndexDocumentsRequest withIsLastPage(Optional<Boolean> isLastPage) {
        Utils.checkNotNull(isLastPage, "isLastPage");
        this.isLastPage = isLastPage;
        return this;
    }

    /**
     * Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
     */
    public BulkIndexDocumentsRequest withForceRestartUpload(boolean forceRestartUpload) {
        Utils.checkNotNull(forceRestartUpload, "forceRestartUpload");
        this.forceRestartUpload = Optional.ofNullable(forceRestartUpload);
        return this;
    }

    /**
     * Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
     */
    public BulkIndexDocumentsRequest withForceRestartUpload(Optional<Boolean> forceRestartUpload) {
        Utils.checkNotNull(forceRestartUpload, "forceRestartUpload");
        this.forceRestartUpload = forceRestartUpload;
        return this;
    }

    /**
     * Datasource of the documents
     */
    public BulkIndexDocumentsRequest withDatasource(String datasource) {
        Utils.checkNotNull(datasource, "datasource");
        this.datasource = datasource;
        return this;
    }

    /**
     * Batch of documents for the datasource
     */
    public BulkIndexDocumentsRequest withDocuments(List<DocumentDefinition> documents) {
        Utils.checkNotNull(documents, "documents");
        this.documents = documents;
        return this;
    }

    /**
     * True if older documents need to be force deleted after the upload completes. Defaults to older documents being deleted asynchronously. This must only be set when `isLastPage = true`
     */
    public BulkIndexDocumentsRequest withDisableStaleDocumentDeletionCheck(boolean disableStaleDocumentDeletionCheck) {
        Utils.checkNotNull(disableStaleDocumentDeletionCheck, "disableStaleDocumentDeletionCheck");
        this.disableStaleDocumentDeletionCheck = Optional.ofNullable(disableStaleDocumentDeletionCheck);
        return this;
    }

    /**
     * True if older documents need to be force deleted after the upload completes. Defaults to older documents being deleted asynchronously. This must only be set when `isLastPage = true`
     */
    public BulkIndexDocumentsRequest withDisableStaleDocumentDeletionCheck(Optional<Boolean> disableStaleDocumentDeletionCheck) {
        Utils.checkNotNull(disableStaleDocumentDeletionCheck, "disableStaleDocumentDeletionCheck");
        this.disableStaleDocumentDeletionCheck = disableStaleDocumentDeletionCheck;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BulkIndexDocumentsRequest other = (BulkIndexDocumentsRequest) o;
        return 
            Objects.deepEquals(this.uploadId, other.uploadId) &&
            Objects.deepEquals(this.isFirstPage, other.isFirstPage) &&
            Objects.deepEquals(this.isLastPage, other.isLastPage) &&
            Objects.deepEquals(this.forceRestartUpload, other.forceRestartUpload) &&
            Objects.deepEquals(this.datasource, other.datasource) &&
            Objects.deepEquals(this.documents, other.documents) &&
            Objects.deepEquals(this.disableStaleDocumentDeletionCheck, other.disableStaleDocumentDeletionCheck);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            uploadId,
            isFirstPage,
            isLastPage,
            forceRestartUpload,
            datasource,
            documents,
            disableStaleDocumentDeletionCheck);
    }
    
    @Override
    public String toString() {
        return Utils.toString(BulkIndexDocumentsRequest.class,
                "uploadId", uploadId,
                "isFirstPage", isFirstPage,
                "isLastPage", isLastPage,
                "forceRestartUpload", forceRestartUpload,
                "datasource", datasource,
                "documents", documents,
                "disableStaleDocumentDeletionCheck", disableStaleDocumentDeletionCheck);
    }
    
    public final static class Builder {
 
        private String uploadId;
 
        private Optional<Boolean> isFirstPage = Optional.empty();
 
        private Optional<Boolean> isLastPage = Optional.empty();
 
        private Optional<Boolean> forceRestartUpload = Optional.empty();
 
        private String datasource;
 
        private List<DocumentDefinition> documents;
 
        private Optional<Boolean> disableStaleDocumentDeletionCheck = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique id that must be used for this bulk upload instance
         */
        public Builder uploadId(String uploadId) {
            Utils.checkNotNull(uploadId, "uploadId");
            this.uploadId = uploadId;
            return this;
        }

        /**
         * true if this is the first page of the upload. Defaults to false
         */
        public Builder isFirstPage(boolean isFirstPage) {
            Utils.checkNotNull(isFirstPage, "isFirstPage");
            this.isFirstPage = Optional.ofNullable(isFirstPage);
            return this;
        }

        /**
         * true if this is the first page of the upload. Defaults to false
         */
        public Builder isFirstPage(Optional<Boolean> isFirstPage) {
            Utils.checkNotNull(isFirstPage, "isFirstPage");
            this.isFirstPage = isFirstPage;
            return this;
        }

        /**
         * true if this is the last page of the upload. Defaults to false
         */
        public Builder isLastPage(boolean isLastPage) {
            Utils.checkNotNull(isLastPage, "isLastPage");
            this.isLastPage = Optional.ofNullable(isLastPage);
            return this;
        }

        /**
         * true if this is the last page of the upload. Defaults to false
         */
        public Builder isLastPage(Optional<Boolean> isLastPage) {
            Utils.checkNotNull(isLastPage, "isLastPage");
            this.isLastPage = isLastPage;
            return this;
        }

        /**
         * Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
         */
        public Builder forceRestartUpload(boolean forceRestartUpload) {
            Utils.checkNotNull(forceRestartUpload, "forceRestartUpload");
            this.forceRestartUpload = Optional.ofNullable(forceRestartUpload);
            return this;
        }

        /**
         * Flag to discard previous upload attempts and start from scratch. Must be specified with isFirstPage=true
         */
        public Builder forceRestartUpload(Optional<Boolean> forceRestartUpload) {
            Utils.checkNotNull(forceRestartUpload, "forceRestartUpload");
            this.forceRestartUpload = forceRestartUpload;
            return this;
        }

        /**
         * Datasource of the documents
         */
        public Builder datasource(String datasource) {
            Utils.checkNotNull(datasource, "datasource");
            this.datasource = datasource;
            return this;
        }

        /**
         * Batch of documents for the datasource
         */
        public Builder documents(List<DocumentDefinition> documents) {
            Utils.checkNotNull(documents, "documents");
            this.documents = documents;
            return this;
        }

        /**
         * True if older documents need to be force deleted after the upload completes. Defaults to older documents being deleted asynchronously. This must only be set when `isLastPage = true`
         */
        public Builder disableStaleDocumentDeletionCheck(boolean disableStaleDocumentDeletionCheck) {
            Utils.checkNotNull(disableStaleDocumentDeletionCheck, "disableStaleDocumentDeletionCheck");
            this.disableStaleDocumentDeletionCheck = Optional.ofNullable(disableStaleDocumentDeletionCheck);
            return this;
        }

        /**
         * True if older documents need to be force deleted after the upload completes. Defaults to older documents being deleted asynchronously. This must only be set when `isLastPage = true`
         */
        public Builder disableStaleDocumentDeletionCheck(Optional<Boolean> disableStaleDocumentDeletionCheck) {
            Utils.checkNotNull(disableStaleDocumentDeletionCheck, "disableStaleDocumentDeletionCheck");
            this.disableStaleDocumentDeletionCheck = disableStaleDocumentDeletionCheck;
            return this;
        }
        
        public BulkIndexDocumentsRequest build() {
            return new BulkIndexDocumentsRequest(
                uploadId,
                isFirstPage,
                isLastPage,
                forceRestartUpload,
                datasource,
                documents,
                disableStaleDocumentDeletionCheck);
        }
    }
}
