/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum PeopleRequestIncludeField {
    BADGES("BADGES"),
    BUSY_EVENTS("BUSY_EVENTS"),
    DOCUMENT_ACTIVITY("DOCUMENT_ACTIVITY"),
    INVITE_INFO("INVITE_INFO"),
    PEOPLE_DISTANCE("PEOPLE_DISTANCE"),
    PERMISSIONS("PERMISSIONS"),
    PEOPLE_DETAILS("PEOPLE_DETAILS"),
    MANAGEMENT_DETAILS("MANAGEMENT_DETAILS"),
    PEOPLE_PROFILE_SETTINGS("PEOPLE_PROFILE_SETTINGS"),
    PEOPLE_WITHOUT_MANAGER("PEOPLE_WITHOUT_MANAGER");

    @JsonValue
    private final String value;

    private PeopleRequestIncludeField(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PeopleRequestIncludeField> fromValue(String value) {
        for (PeopleRequestIncludeField o: PeopleRequestIncludeField.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

