/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.glean.api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SocialNetworkDefinition
 * 
 * <p>Employee's social network profile
 */
public class SocialNetworkDefinition {

    /**
     * Possible values are "twitter", "linkedin".
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * Human-readable profile name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profileName")
    private Optional<String> profileName;

    /**
     * Link to profile.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profileUrl")
    private Optional<String> profileUrl;

    @JsonCreator
    public SocialNetworkDefinition(
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("profileName") Optional<String> profileName,
            @JsonProperty("profileUrl") Optional<String> profileUrl) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(profileName, "profileName");
        Utils.checkNotNull(profileUrl, "profileUrl");
        this.name = name;
        this.profileName = profileName;
        this.profileUrl = profileUrl;
    }
    
    public SocialNetworkDefinition() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Possible values are "twitter", "linkedin".
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * Human-readable profile name.
     */
    @JsonIgnore
    public Optional<String> profileName() {
        return profileName;
    }

    /**
     * Link to profile.
     */
    @JsonIgnore
    public Optional<String> profileUrl() {
        return profileUrl;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Possible values are "twitter", "linkedin".
     */
    public SocialNetworkDefinition withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }

    /**
     * Possible values are "twitter", "linkedin".
     */
    public SocialNetworkDefinition withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * Human-readable profile name.
     */
    public SocialNetworkDefinition withProfileName(String profileName) {
        Utils.checkNotNull(profileName, "profileName");
        this.profileName = Optional.ofNullable(profileName);
        return this;
    }

    /**
     * Human-readable profile name.
     */
    public SocialNetworkDefinition withProfileName(Optional<String> profileName) {
        Utils.checkNotNull(profileName, "profileName");
        this.profileName = profileName;
        return this;
    }

    /**
     * Link to profile.
     */
    public SocialNetworkDefinition withProfileUrl(String profileUrl) {
        Utils.checkNotNull(profileUrl, "profileUrl");
        this.profileUrl = Optional.ofNullable(profileUrl);
        return this;
    }

    /**
     * Link to profile.
     */
    public SocialNetworkDefinition withProfileUrl(Optional<String> profileUrl) {
        Utils.checkNotNull(profileUrl, "profileUrl");
        this.profileUrl = profileUrl;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SocialNetworkDefinition other = (SocialNetworkDefinition) o;
        return 
            Objects.deepEquals(this.name, other.name) &&
            Objects.deepEquals(this.profileName, other.profileName) &&
            Objects.deepEquals(this.profileUrl, other.profileUrl);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            name,
            profileName,
            profileUrl);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SocialNetworkDefinition.class,
                "name", name,
                "profileName", profileName,
                "profileUrl", profileUrl);
    }
    
    public final static class Builder {
 
        private Optional<String> name = Optional.empty();
 
        private Optional<String> profileName = Optional.empty();
 
        private Optional<String> profileUrl = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Possible values are "twitter", "linkedin".
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * Possible values are "twitter", "linkedin".
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * Human-readable profile name.
         */
        public Builder profileName(String profileName) {
            Utils.checkNotNull(profileName, "profileName");
            this.profileName = Optional.ofNullable(profileName);
            return this;
        }

        /**
         * Human-readable profile name.
         */
        public Builder profileName(Optional<String> profileName) {
            Utils.checkNotNull(profileName, "profileName");
            this.profileName = profileName;
            return this;
        }

        /**
         * Link to profile.
         */
        public Builder profileUrl(String profileUrl) {
            Utils.checkNotNull(profileUrl, "profileUrl");
            this.profileUrl = Optional.ofNullable(profileUrl);
            return this;
        }

        /**
         * Link to profile.
         */
        public Builder profileUrl(Optional<String> profileUrl) {
            Utils.checkNotNull(profileUrl, "profileUrl");
            this.profileUrl = profileUrl;
            return this;
        }
        
        public SocialNetworkDefinition build() {
            return new SocialNetworkDefinition(
                name,
                profileName,
                profileUrl);
        }
    }
}
