/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.models.components.AddCollectionItemsRequest;
import com.glean.api_client.utils.SpeakeasyMetadata;
import com.glean.api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public class AddcollectionitemsRequest {

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Scio-Actas")
    private Optional<String> xScioActas;

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Glean-Auth-Type")
    private Optional<String> xGleanAuthType;

    /**
     * Data describing the add operation.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private AddCollectionItemsRequest addCollectionItemsRequest;

    @JsonCreator
    public AddcollectionitemsRequest(
            Optional<String> xScioActas,
            Optional<String> xGleanAuthType,
            AddCollectionItemsRequest addCollectionItemsRequest) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        Utils.checkNotNull(addCollectionItemsRequest, "addCollectionItemsRequest");
        this.xScioActas = xScioActas;
        this.xGleanAuthType = xGleanAuthType;
        this.addCollectionItemsRequest = addCollectionItemsRequest;
    }
    
    public AddcollectionitemsRequest(
            AddCollectionItemsRequest addCollectionItemsRequest) {
        this(Optional.empty(), Optional.empty(), addCollectionItemsRequest);
    }

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    @JsonIgnore
    public Optional<String> xScioActas() {
        return xScioActas;
    }

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    @JsonIgnore
    public Optional<String> xGleanAuthType() {
        return xGleanAuthType;
    }

    /**
     * Data describing the add operation.
     */
    @JsonIgnore
    public AddCollectionItemsRequest addCollectionItemsRequest() {
        return addCollectionItemsRequest;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    public AddcollectionitemsRequest withXScioActas(String xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = Optional.ofNullable(xScioActas);
        return this;
    }

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    public AddcollectionitemsRequest withXScioActas(Optional<String> xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = xScioActas;
        return this;
    }

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    public AddcollectionitemsRequest withXGleanAuthType(String xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = Optional.ofNullable(xGleanAuthType);
        return this;
    }

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    public AddcollectionitemsRequest withXGleanAuthType(Optional<String> xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = xGleanAuthType;
        return this;
    }

    /**
     * Data describing the add operation.
     */
    public AddcollectionitemsRequest withAddCollectionItemsRequest(AddCollectionItemsRequest addCollectionItemsRequest) {
        Utils.checkNotNull(addCollectionItemsRequest, "addCollectionItemsRequest");
        this.addCollectionItemsRequest = addCollectionItemsRequest;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AddcollectionitemsRequest other = (AddcollectionitemsRequest) o;
        return 
            Objects.deepEquals(this.xScioActas, other.xScioActas) &&
            Objects.deepEquals(this.xGleanAuthType, other.xGleanAuthType) &&
            Objects.deepEquals(this.addCollectionItemsRequest, other.addCollectionItemsRequest);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            xScioActas,
            xGleanAuthType,
            addCollectionItemsRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AddcollectionitemsRequest.class,
                "xScioActas", xScioActas,
                "xGleanAuthType", xGleanAuthType,
                "addCollectionItemsRequest", addCollectionItemsRequest);
    }
    
    public final static class Builder {
 
        private Optional<String> xScioActas = Optional.empty();
 
        private Optional<String> xGleanAuthType = Optional.empty();
 
        private AddCollectionItemsRequest addCollectionItemsRequest;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
         */
        public Builder xScioActas(String xScioActas) {
            Utils.checkNotNull(xScioActas, "xScioActas");
            this.xScioActas = Optional.ofNullable(xScioActas);
            return this;
        }

        /**
         * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
         */
        public Builder xScioActas(Optional<String> xScioActas) {
            Utils.checkNotNull(xScioActas, "xScioActas");
            this.xScioActas = xScioActas;
            return this;
        }

        /**
         * Auth type being used to access the endpoint (should be non-empty only for global tokens).
         */
        public Builder xGleanAuthType(String xGleanAuthType) {
            Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
            this.xGleanAuthType = Optional.ofNullable(xGleanAuthType);
            return this;
        }

        /**
         * Auth type being used to access the endpoint (should be non-empty only for global tokens).
         */
        public Builder xGleanAuthType(Optional<String> xGleanAuthType) {
            Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
            this.xGleanAuthType = xGleanAuthType;
            return this;
        }

        /**
         * Data describing the add operation.
         */
        public Builder addCollectionItemsRequest(AddCollectionItemsRequest addCollectionItemsRequest) {
            Utils.checkNotNull(addCollectionItemsRequest, "addCollectionItemsRequest");
            this.addCollectionItemsRequest = addCollectionItemsRequest;
            return this;
        }
        
        public AddcollectionitemsRequest build() {
            return new AddcollectionitemsRequest(
                xScioActas,
                xGleanAuthType,
                addCollectionItemsRequest);
        }
    }
}
