/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.utils.SpeakeasyMetadata;
import com.glean.api_client.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public class ChatRequest {

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Scio-Actas")
    private Optional<String> xScioActas;

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Glean-Auth-Type")
    private Optional<String> xGleanAuthType;

    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=timezoneOffset")
    private Optional<Long> timezoneOffset;

    /**
     * Includes chat history for Glean AI to respond to.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.glean.api_client.models.components.ChatRequest chatRequest;

    @JsonCreator
    public ChatRequest(
            Optional<String> xScioActas,
            Optional<String> xGleanAuthType,
            Optional<Long> timezoneOffset,
            com.glean.api_client.models.components.ChatRequest chatRequest) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        Utils.checkNotNull(chatRequest, "chatRequest");
        this.xScioActas = xScioActas;
        this.xGleanAuthType = xGleanAuthType;
        this.timezoneOffset = timezoneOffset;
        this.chatRequest = chatRequest;
    }
    
    public ChatRequest(
            com.glean.api_client.models.components.ChatRequest chatRequest) {
        this(Optional.empty(), Optional.empty(), Optional.empty(), chatRequest);
    }

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    @JsonIgnore
    public Optional<String> xScioActas() {
        return xScioActas;
    }

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    @JsonIgnore
    public Optional<String> xGleanAuthType() {
        return xGleanAuthType;
    }

    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
     */
    @JsonIgnore
    public Optional<Long> timezoneOffset() {
        return timezoneOffset;
    }

    /**
     * Includes chat history for Glean AI to respond to.
     */
    @JsonIgnore
    public com.glean.api_client.models.components.ChatRequest chatRequest() {
        return chatRequest;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    public ChatRequest withXScioActas(String xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = Optional.ofNullable(xScioActas);
        return this;
    }

    /**
     * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
     */
    public ChatRequest withXScioActas(Optional<String> xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = xScioActas;
        return this;
    }

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    public ChatRequest withXGleanAuthType(String xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = Optional.ofNullable(xGleanAuthType);
        return this;
    }

    /**
     * Auth type being used to access the endpoint (should be non-empty only for global tokens).
     */
    public ChatRequest withXGleanAuthType(Optional<String> xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = xGleanAuthType;
        return this;
    }

    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
     */
    public ChatRequest withTimezoneOffset(long timezoneOffset) {
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        this.timezoneOffset = Optional.ofNullable(timezoneOffset);
        return this;
    }

    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
     */
    public ChatRequest withTimezoneOffset(Optional<Long> timezoneOffset) {
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        this.timezoneOffset = timezoneOffset;
        return this;
    }

    /**
     * Includes chat history for Glean AI to respond to.
     */
    public ChatRequest withChatRequest(com.glean.api_client.models.components.ChatRequest chatRequest) {
        Utils.checkNotNull(chatRequest, "chatRequest");
        this.chatRequest = chatRequest;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ChatRequest other = (ChatRequest) o;
        return 
            Objects.deepEquals(this.xScioActas, other.xScioActas) &&
            Objects.deepEquals(this.xGleanAuthType, other.xGleanAuthType) &&
            Objects.deepEquals(this.timezoneOffset, other.timezoneOffset) &&
            Objects.deepEquals(this.chatRequest, other.chatRequest);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            xScioActas,
            xGleanAuthType,
            timezoneOffset,
            chatRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ChatRequest.class,
                "xScioActas", xScioActas,
                "xGleanAuthType", xGleanAuthType,
                "timezoneOffset", timezoneOffset,
                "chatRequest", chatRequest);
    }
    
    public final static class Builder {
 
        private Optional<String> xScioActas = Optional.empty();
 
        private Optional<String> xGleanAuthType = Optional.empty();
 
        private Optional<Long> timezoneOffset = Optional.empty();
 
        private com.glean.api_client.models.components.ChatRequest chatRequest;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
         */
        public Builder xScioActas(String xScioActas) {
            Utils.checkNotNull(xScioActas, "xScioActas");
            this.xScioActas = Optional.ofNullable(xScioActas);
            return this;
        }

        /**
         * Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
         */
        public Builder xScioActas(Optional<String> xScioActas) {
            Utils.checkNotNull(xScioActas, "xScioActas");
            this.xScioActas = xScioActas;
            return this;
        }

        /**
         * Auth type being used to access the endpoint (should be non-empty only for global tokens).
         */
        public Builder xGleanAuthType(String xGleanAuthType) {
            Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
            this.xGleanAuthType = Optional.ofNullable(xGleanAuthType);
            return this;
        }

        /**
         * Auth type being used to access the endpoint (should be non-empty only for global tokens).
         */
        public Builder xGleanAuthType(Optional<String> xGleanAuthType) {
            Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
            this.xGleanAuthType = xGleanAuthType;
            return this;
        }

        /**
         * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
         */
        public Builder timezoneOffset(long timezoneOffset) {
            Utils.checkNotNull(timezoneOffset, "timezoneOffset");
            this.timezoneOffset = Optional.ofNullable(timezoneOffset);
            return this;
        }

        /**
         * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
         */
        public Builder timezoneOffset(Optional<Long> timezoneOffset) {
            Utils.checkNotNull(timezoneOffset, "timezoneOffset");
            this.timezoneOffset = timezoneOffset;
            return this;
        }

        /**
         * Includes chat history for Glean AI to respond to.
         */
        public Builder chatRequest(com.glean.api_client.models.components.ChatRequest chatRequest) {
            Utils.checkNotNull(chatRequest, "chatRequest");
            this.chatRequest = chatRequest;
            return this;
        }
        
        public ChatRequest build() {
            return new ChatRequest(
                xScioActas,
                xGleanAuthType,
                timezoneOffset,
                chatRequest);
        }
    }
}
