/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.models.components.CreateAnswerBoardResponse;
import com.glean.api_client.utils.Response;
import com.glean.api_client.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class CreateanswerboardResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * OK
     */
    private Optional<? extends CreateAnswerBoardResponse> createAnswerBoardResponse;

    @JsonCreator
    public CreateanswerboardResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends CreateAnswerBoardResponse> createAnswerBoardResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(createAnswerBoardResponse, "createAnswerBoardResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.createAnswerBoardResponse = createAnswerBoardResponse;
    }
    
    public CreateanswerboardResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CreateAnswerBoardResponse> createAnswerBoardResponse() {
        return (Optional<CreateAnswerBoardResponse>) createAnswerBoardResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public CreateanswerboardResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateanswerboardResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateanswerboardResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public CreateanswerboardResponse withCreateAnswerBoardResponse(CreateAnswerBoardResponse createAnswerBoardResponse) {
        Utils.checkNotNull(createAnswerBoardResponse, "createAnswerBoardResponse");
        this.createAnswerBoardResponse = Optional.ofNullable(createAnswerBoardResponse);
        return this;
    }

    /**
     * OK
     */
    public CreateanswerboardResponse withCreateAnswerBoardResponse(Optional<? extends CreateAnswerBoardResponse> createAnswerBoardResponse) {
        Utils.checkNotNull(createAnswerBoardResponse, "createAnswerBoardResponse");
        this.createAnswerBoardResponse = createAnswerBoardResponse;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateanswerboardResponse other = (CreateanswerboardResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.createAnswerBoardResponse, other.createAnswerBoardResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            createAnswerBoardResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateanswerboardResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "createAnswerBoardResponse", createAnswerBoardResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends CreateAnswerBoardResponse> createAnswerBoardResponse = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * OK
         */
        public Builder createAnswerBoardResponse(CreateAnswerBoardResponse createAnswerBoardResponse) {
            Utils.checkNotNull(createAnswerBoardResponse, "createAnswerBoardResponse");
            this.createAnswerBoardResponse = Optional.ofNullable(createAnswerBoardResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder createAnswerBoardResponse(Optional<? extends CreateAnswerBoardResponse> createAnswerBoardResponse) {
            Utils.checkNotNull(createAnswerBoardResponse, "createAnswerBoardResponse");
            this.createAnswerBoardResponse = createAnswerBoardResponse;
            return this;
        }
        
        public CreateanswerboardResponse build() {
            return new CreateanswerboardResponse(
                contentType,
                statusCode,
                rawResponse,
                createAnswerBoardResponse);
        }
    }
}
