/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.glean.api_client.models.components.CreateShortcutRequest;
import com.glean.api_client.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class CreateshortcutRequestBuilder {

    private Optional<String> xScioActas = Optional.empty();
    private Optional<String> xGleanAuthType = Optional.empty();
    private CreateShortcutRequest createShortcutRequest;
    private final SDKMethodInterfaces.MethodCallCreateshortcut sdk;

    public CreateshortcutRequestBuilder(SDKMethodInterfaces.MethodCallCreateshortcut sdk) {
        this.sdk = sdk;
    }
                
    public CreateshortcutRequestBuilder xScioActas(String xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = Optional.of(xScioActas);
        return this;
    }

    public CreateshortcutRequestBuilder xScioActas(Optional<String> xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = xScioActas;
        return this;
    }
                
    public CreateshortcutRequestBuilder xGleanAuthType(String xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = Optional.of(xGleanAuthType);
        return this;
    }

    public CreateshortcutRequestBuilder xGleanAuthType(Optional<String> xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = xGleanAuthType;
        return this;
    }

    public CreateshortcutRequestBuilder createShortcutRequest(CreateShortcutRequest createShortcutRequest) {
        Utils.checkNotNull(createShortcutRequest, "createShortcutRequest");
        this.createShortcutRequest = createShortcutRequest;
        return this;
    }

    public CreateshortcutResponse call() throws Exception {

        return sdk.create(
            xScioActas,
            xGleanAuthType,
            createShortcutRequest);
    }
}
