/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.models.components.DeleteAnswerBoardsResponse;
import com.glean.api_client.utils.Response;
import com.glean.api_client.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class DeleteanswerboardsResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * OK
     */
    private Optional<? extends DeleteAnswerBoardsResponse> deleteAnswerBoardsResponse;

    @JsonCreator
    public DeleteanswerboardsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends DeleteAnswerBoardsResponse> deleteAnswerBoardsResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(deleteAnswerBoardsResponse, "deleteAnswerBoardsResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.deleteAnswerBoardsResponse = deleteAnswerBoardsResponse;
    }
    
    public DeleteanswerboardsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<DeleteAnswerBoardsResponse> deleteAnswerBoardsResponse() {
        return (Optional<DeleteAnswerBoardsResponse>) deleteAnswerBoardsResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public DeleteanswerboardsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public DeleteanswerboardsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public DeleteanswerboardsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public DeleteanswerboardsResponse withDeleteAnswerBoardsResponse(DeleteAnswerBoardsResponse deleteAnswerBoardsResponse) {
        Utils.checkNotNull(deleteAnswerBoardsResponse, "deleteAnswerBoardsResponse");
        this.deleteAnswerBoardsResponse = Optional.ofNullable(deleteAnswerBoardsResponse);
        return this;
    }

    /**
     * OK
     */
    public DeleteanswerboardsResponse withDeleteAnswerBoardsResponse(Optional<? extends DeleteAnswerBoardsResponse> deleteAnswerBoardsResponse) {
        Utils.checkNotNull(deleteAnswerBoardsResponse, "deleteAnswerBoardsResponse");
        this.deleteAnswerBoardsResponse = deleteAnswerBoardsResponse;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteanswerboardsResponse other = (DeleteanswerboardsResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.deleteAnswerBoardsResponse, other.deleteAnswerBoardsResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            deleteAnswerBoardsResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteanswerboardsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "deleteAnswerBoardsResponse", deleteAnswerBoardsResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends DeleteAnswerBoardsResponse> deleteAnswerBoardsResponse = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * OK
         */
        public Builder deleteAnswerBoardsResponse(DeleteAnswerBoardsResponse deleteAnswerBoardsResponse) {
            Utils.checkNotNull(deleteAnswerBoardsResponse, "deleteAnswerBoardsResponse");
            this.deleteAnswerBoardsResponse = Optional.ofNullable(deleteAnswerBoardsResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder deleteAnswerBoardsResponse(Optional<? extends DeleteAnswerBoardsResponse> deleteAnswerBoardsResponse) {
            Utils.checkNotNull(deleteAnswerBoardsResponse, "deleteAnswerBoardsResponse");
            this.deleteAnswerBoardsResponse = deleteAnswerBoardsResponse;
            return this;
        }
        
        public DeleteanswerboardsResponse build() {
            return new DeleteanswerboardsResponse(
                contentType,
                statusCode,
                rawResponse,
                deleteAnswerBoardsResponse);
        }
    }
}
