/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.glean.api_client.models.components.EditAnswerRequest;
import com.glean.api_client.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class EditanswerRequestBuilder {

    private Optional<String> xScioActas = Optional.empty();
    private Optional<String> xGleanAuthType = Optional.empty();
    private EditAnswerRequest editAnswerRequest;
    private final SDKMethodInterfaces.MethodCallEditanswer sdk;

    public EditanswerRequestBuilder(SDKMethodInterfaces.MethodCallEditanswer sdk) {
        this.sdk = sdk;
    }
                
    public EditanswerRequestBuilder xScioActas(String xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = Optional.of(xScioActas);
        return this;
    }

    public EditanswerRequestBuilder xScioActas(Optional<String> xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = xScioActas;
        return this;
    }
                
    public EditanswerRequestBuilder xGleanAuthType(String xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = Optional.of(xGleanAuthType);
        return this;
    }

    public EditanswerRequestBuilder xGleanAuthType(Optional<String> xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = xGleanAuthType;
        return this;
    }

    public EditanswerRequestBuilder editAnswerRequest(EditAnswerRequest editAnswerRequest) {
        Utils.checkNotNull(editAnswerRequest, "editAnswerRequest");
        this.editAnswerRequest = editAnswerRequest;
        return this;
    }

    public EditanswerResponse call() throws Exception {

        return sdk.edit(
            xScioActas,
            xGleanAuthType,
            editAnswerRequest);
    }
}
