/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.glean.api_client.models.components.DeleteTeamRequest;
import com.glean.api_client.utils.Utils;
import java.lang.Exception;

public class PostApiIndexV1DeleteteamRequestBuilder {

    private DeleteTeamRequest request;
    private final SDKMethodInterfaces.MethodCallPostApiIndexV1Deleteteam sdk;

    public PostApiIndexV1DeleteteamRequestBuilder(SDKMethodInterfaces.MethodCallPostApiIndexV1Deleteteam sdk) {
        this.sdk = sdk;
    }

    public PostApiIndexV1DeleteteamRequestBuilder request(DeleteTeamRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PostApiIndexV1DeleteteamResponse call() throws Exception {

        return sdk.deleteTeam(
            request);
    }
}
