/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.glean.api_client.models.components.GreenlistUsersRequest;
import com.glean.api_client.utils.Utils;
import java.lang.Exception;

public class PostApiIndexV1BetausersRequestBuilder {

    private GreenlistUsersRequest request;
    private final SDKMethodInterfaces.MethodCallPostApiIndexV1Betausers sdk;

    public PostApiIndexV1BetausersRequestBuilder(SDKMethodInterfaces.MethodCallPostApiIndexV1Betausers sdk) {
        this.sdk = sdk;
    }

    public PostApiIndexV1BetausersRequestBuilder request(GreenlistUsersRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PostApiIndexV1BetausersResponse call() throws Exception {

        return sdk.authorizeBetaUsers(
            request);
    }
}
