/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.models.components.GetDocumentStatusResponse;
import com.glean.api_client.utils.Response;
import com.glean.api_client.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class PostApiIndexV1GetdocumentstatusResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * OK
     */
    private Optional<? extends GetDocumentStatusResponse> getDocumentStatusResponse;

    @JsonCreator
    public PostApiIndexV1GetdocumentstatusResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends GetDocumentStatusResponse> getDocumentStatusResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(getDocumentStatusResponse, "getDocumentStatusResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.getDocumentStatusResponse = getDocumentStatusResponse;
    }
    
    public PostApiIndexV1GetdocumentstatusResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetDocumentStatusResponse> getDocumentStatusResponse() {
        return (Optional<GetDocumentStatusResponse>) getDocumentStatusResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public PostApiIndexV1GetdocumentstatusResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public PostApiIndexV1GetdocumentstatusResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public PostApiIndexV1GetdocumentstatusResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public PostApiIndexV1GetdocumentstatusResponse withGetDocumentStatusResponse(GetDocumentStatusResponse getDocumentStatusResponse) {
        Utils.checkNotNull(getDocumentStatusResponse, "getDocumentStatusResponse");
        this.getDocumentStatusResponse = Optional.ofNullable(getDocumentStatusResponse);
        return this;
    }

    /**
     * OK
     */
    public PostApiIndexV1GetdocumentstatusResponse withGetDocumentStatusResponse(Optional<? extends GetDocumentStatusResponse> getDocumentStatusResponse) {
        Utils.checkNotNull(getDocumentStatusResponse, "getDocumentStatusResponse");
        this.getDocumentStatusResponse = getDocumentStatusResponse;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PostApiIndexV1GetdocumentstatusResponse other = (PostApiIndexV1GetdocumentstatusResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.getDocumentStatusResponse, other.getDocumentStatusResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            getDocumentStatusResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PostApiIndexV1GetdocumentstatusResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "getDocumentStatusResponse", getDocumentStatusResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends GetDocumentStatusResponse> getDocumentStatusResponse = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * OK
         */
        public Builder getDocumentStatusResponse(GetDocumentStatusResponse getDocumentStatusResponse) {
            Utils.checkNotNull(getDocumentStatusResponse, "getDocumentStatusResponse");
            this.getDocumentStatusResponse = Optional.ofNullable(getDocumentStatusResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder getDocumentStatusResponse(Optional<? extends GetDocumentStatusResponse> getDocumentStatusResponse) {
            Utils.checkNotNull(getDocumentStatusResponse, "getDocumentStatusResponse");
            this.getDocumentStatusResponse = getDocumentStatusResponse;
            return this;
        }
        
        public PostApiIndexV1GetdocumentstatusResponse build() {
            return new PostApiIndexV1GetdocumentstatusResponse(
                contentType,
                statusCode,
                rawResponse,
                getDocumentStatusResponse);
        }
    }
}
