/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.models.operations;

import com.glean.api_client.models.components.RemoveCredentialRequest;
import com.glean.api_client.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class RemovecredentialRequestBuilder {

    private Optional<String> xScioActas = Optional.empty();
    private Optional<String> xGleanAuthType = Optional.empty();
    private RemoveCredentialRequest removeCredentialRequest;
    private final SDKMethodInterfaces.MethodCallRemovecredential sdk;

    public RemovecredentialRequestBuilder(SDKMethodInterfaces.MethodCallRemovecredential sdk) {
        this.sdk = sdk;
    }
                
    public RemovecredentialRequestBuilder xScioActas(String xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = Optional.of(xScioActas);
        return this;
    }

    public RemovecredentialRequestBuilder xScioActas(Optional<String> xScioActas) {
        Utils.checkNotNull(xScioActas, "xScioActas");
        this.xScioActas = xScioActas;
        return this;
    }
                
    public RemovecredentialRequestBuilder xGleanAuthType(String xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = Optional.of(xGleanAuthType);
        return this;
    }

    public RemovecredentialRequestBuilder xGleanAuthType(Optional<String> xGleanAuthType) {
        Utils.checkNotNull(xGleanAuthType, "xGleanAuthType");
        this.xGleanAuthType = xGleanAuthType;
        return this;
    }

    public RemovecredentialRequestBuilder removeCredentialRequest(RemoveCredentialRequest removeCredentialRequest) {
        Utils.checkNotNull(removeCredentialRequest, "removeCredentialRequest");
        this.removeCredentialRequest = removeCredentialRequest;
        return this;
    }

    public RemovecredentialResponse call() throws Exception {

        return sdk.removeCredential(
            xScioActas,
            xGleanAuthType,
            removeCredentialRequest);
    }
}
