/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.operations.DownloadpolicycsvRequest;
import com.glean.api_client.glean_api_client.operations.Downloadpolicycsv;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class DownloadpolicycsvRequestBuilder {

    private String id;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DownloadpolicycsvRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DownloadpolicycsvRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }


    private DownloadpolicycsvRequest buildRequest() {

        DownloadpolicycsvRequest request = new DownloadpolicycsvRequest(id);

        return request;
    }

    public CompletableFuture<DownloadpolicycsvResponse> call() {
        
        AsyncRequestOperation<DownloadpolicycsvRequest, DownloadpolicycsvResponse> operation
              = new Downloadpolicycsv.Async(sdkConfiguration, _headers);
        DownloadpolicycsvRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
