/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.EditCollectionItemRequest;
import com.glean.api_client.glean_api_client.models.operations.EditcollectionitemRequest;
import com.glean.api_client.glean_api_client.operations.Editcollectionitem;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class EditcollectionitemRequestBuilder {

    private Optional<String> locale = Optional.empty();
    private EditCollectionItemRequest editCollectionItemRequest;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public EditcollectionitemRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public EditcollectionitemRequestBuilder locale(String locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = Optional.of(locale);
        return this;
    }

    public EditcollectionitemRequestBuilder locale(Optional<String> locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = locale;
        return this;
    }

    public EditcollectionitemRequestBuilder editCollectionItemRequest(EditCollectionItemRequest editCollectionItemRequest) {
        Utils.checkNotNull(editCollectionItemRequest, "editCollectionItemRequest");
        this.editCollectionItemRequest = editCollectionItemRequest;
        return this;
    }


    private EditcollectionitemRequest buildRequest() {

        EditcollectionitemRequest request = new EditcollectionitemRequest(locale,
            editCollectionItemRequest);

        return request;
    }

    public CompletableFuture<EditcollectionitemResponse> call() {
        
        AsyncRequestOperation<EditcollectionitemRequest, EditcollectionitemResponse> operation
              = new Editcollectionitem.Async(sdkConfiguration, _headers);
        EditcollectionitemRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
