/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.EditCollectionItemRequest;
import com.glean.api_client.glean_api_client.operations.Editcollectionitem;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class EditcollectionitemRequestBuilder {

    private EditCollectionItemRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public EditcollectionitemRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public EditcollectionitemRequestBuilder request(EditCollectionItemRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<EditcollectionitemResponse> call() throws Exception {
        
        AsyncRequestOperation<EditCollectionItemRequest, EditcollectionitemResponse> operation
              = new Editcollectionitem.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
