/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.Feedback;
import com.glean.api_client.glean_api_client.models.operations.FeedbackRequest;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class FeedbackRequestBuilder {

    private Optional<String> feedbackQueryParameter = Optional.empty();
    private Optional<? extends Feedback> feedback1 = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public FeedbackRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public FeedbackRequestBuilder feedbackQueryParameter(String feedbackQueryParameter) {
        Utils.checkNotNull(feedbackQueryParameter, "feedbackQueryParameter");
        this.feedbackQueryParameter = Optional.of(feedbackQueryParameter);
        return this;
    }

    public FeedbackRequestBuilder feedbackQueryParameter(Optional<String> feedbackQueryParameter) {
        Utils.checkNotNull(feedbackQueryParameter, "feedbackQueryParameter");
        this.feedbackQueryParameter = feedbackQueryParameter;
        return this;
    }
                
    public FeedbackRequestBuilder feedback1(Feedback feedback1) {
        Utils.checkNotNull(feedback1, "feedback1");
        this.feedback1 = Optional.of(feedback1);
        return this;
    }

    public FeedbackRequestBuilder feedback1(Optional<? extends Feedback> feedback1) {
        Utils.checkNotNull(feedback1, "feedback1");
        this.feedback1 = feedback1;
        return this;
    }


    private FeedbackRequest buildRequest() {

        FeedbackRequest request = new FeedbackRequest(feedbackQueryParameter,
            feedback1);

        return request;
    }

    public CompletableFuture<FeedbackResponse> call() throws Exception {
        
        AsyncRequestOperation<FeedbackRequest, FeedbackResponse> operation
              = new com.glean.api_client.glean_api_client.operations.Feedback.Async(sdkConfiguration, _headers);
        FeedbackRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
