/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c2fb9980232
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.operations.GetAgentSchemasRequest;
import com.glean.api_client.glean_api_client.operations.GetAgentSchemas;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class GetAgentSchemasRequestBuilder {

    private Optional<String> locale = Optional.empty();
    private Optional<Long> timezoneOffset = Optional.empty();
    private String agentId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetAgentSchemasRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetAgentSchemasRequestBuilder locale(String locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = Optional.of(locale);
        return this;
    }

    public GetAgentSchemasRequestBuilder locale(Optional<String> locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = locale;
        return this;
    }
                
    public GetAgentSchemasRequestBuilder timezoneOffset(long timezoneOffset) {
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        this.timezoneOffset = Optional.of(timezoneOffset);
        return this;
    }

    public GetAgentSchemasRequestBuilder timezoneOffset(Optional<Long> timezoneOffset) {
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        this.timezoneOffset = timezoneOffset;
        return this;
    }

    public GetAgentSchemasRequestBuilder agentId(String agentId) {
        Utils.checkNotNull(agentId, "agentId");
        this.agentId = agentId;
        return this;
    }


    private GetAgentSchemasRequest buildRequest() {

        GetAgentSchemasRequest request = new GetAgentSchemasRequest(locale,
            timezoneOffset,
            agentId);

        return request;
    }

    public CompletableFuture<GetAgentSchemasResponse> call() {
        
        AsyncRequestOperation<GetAgentSchemasRequest, GetAgentSchemasResponse> operation
              = new GetAgentSchemas.Async(sdkConfiguration, _headers);
        GetAgentSchemasRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
