/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.models.components.ListShortcutsPaginatedResponse;
import com.glean.api_client.glean_api_client.utils.AsyncResponse;
import com.glean.api_client.glean_api_client.utils.Blob;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListshortcutsResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * OK
     */
    private Optional<? extends ListShortcutsPaginatedResponse> listShortcutsPaginatedResponse;

    @JsonCreator
    public ListshortcutsResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends ListShortcutsPaginatedResponse> listShortcutsPaginatedResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(listShortcutsPaginatedResponse, "listShortcutsPaginatedResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.listShortcutsPaginatedResponse = listShortcutsPaginatedResponse;
    }
    
    public ListshortcutsResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ListShortcutsPaginatedResponse> listShortcutsPaginatedResponse() {
        return (Optional<ListShortcutsPaginatedResponse>) listShortcutsPaginatedResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListshortcutsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListshortcutsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListshortcutsResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public ListshortcutsResponse withListShortcutsPaginatedResponse(ListShortcutsPaginatedResponse listShortcutsPaginatedResponse) {
        Utils.checkNotNull(listShortcutsPaginatedResponse, "listShortcutsPaginatedResponse");
        this.listShortcutsPaginatedResponse = Optional.ofNullable(listShortcutsPaginatedResponse);
        return this;
    }


    /**
     * OK
     */
    public ListshortcutsResponse withListShortcutsPaginatedResponse(Optional<? extends ListShortcutsPaginatedResponse> listShortcutsPaginatedResponse) {
        Utils.checkNotNull(listShortcutsPaginatedResponse, "listShortcutsPaginatedResponse");
        this.listShortcutsPaginatedResponse = listShortcutsPaginatedResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListshortcutsResponse other = (ListshortcutsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.listShortcutsPaginatedResponse, other.listShortcutsPaginatedResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            listShortcutsPaginatedResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListshortcutsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "listShortcutsPaginatedResponse", listShortcutsPaginatedResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends ListShortcutsPaginatedResponse> listShortcutsPaginatedResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * OK
         */
        public Builder listShortcutsPaginatedResponse(ListShortcutsPaginatedResponse listShortcutsPaginatedResponse) {
            Utils.checkNotNull(listShortcutsPaginatedResponse, "listShortcutsPaginatedResponse");
            this.listShortcutsPaginatedResponse = Optional.ofNullable(listShortcutsPaginatedResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder listShortcutsPaginatedResponse(Optional<? extends ListShortcutsPaginatedResponse> listShortcutsPaginatedResponse) {
            Utils.checkNotNull(listShortcutsPaginatedResponse, "listShortcutsPaginatedResponse");
            this.listShortcutsPaginatedResponse = listShortcutsPaginatedResponse;
            return this;
        }

        public ListshortcutsResponse build() {

            return new ListshortcutsResponse(
                contentType, statusCode, rawResponse,
                listShortcutsPaginatedResponse);
        }

    }
}
