/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbcea0df0cb3
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.models.components.PlatformTriggerGetResponse;
import com.glean.api_client.glean_api_client.utils.AsyncResponse;
import com.glean.api_client.glean_api_client.utils.Blob;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class PlatformTriggersGetResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Successful response.
     */
    private Optional<? extends PlatformTriggerGetResponse> platformTriggerGetResponse;

    @JsonCreator
    public PlatformTriggersGetResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends PlatformTriggerGetResponse> platformTriggerGetResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(platformTriggerGetResponse, "platformTriggerGetResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.platformTriggerGetResponse = platformTriggerGetResponse;
    }
    
    public PlatformTriggersGetResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Successful response.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PlatformTriggerGetResponse> platformTriggerGetResponse() {
        return (Optional<PlatformTriggerGetResponse>) platformTriggerGetResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public PlatformTriggersGetResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public PlatformTriggersGetResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public PlatformTriggersGetResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Successful response.
     */
    public PlatformTriggersGetResponse withPlatformTriggerGetResponse(PlatformTriggerGetResponse platformTriggerGetResponse) {
        Utils.checkNotNull(platformTriggerGetResponse, "platformTriggerGetResponse");
        this.platformTriggerGetResponse = Optional.ofNullable(platformTriggerGetResponse);
        return this;
    }


    /**
     * Successful response.
     */
    public PlatformTriggersGetResponse withPlatformTriggerGetResponse(Optional<? extends PlatformTriggerGetResponse> platformTriggerGetResponse) {
        Utils.checkNotNull(platformTriggerGetResponse, "platformTriggerGetResponse");
        this.platformTriggerGetResponse = platformTriggerGetResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlatformTriggersGetResponse other = (PlatformTriggersGetResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.platformTriggerGetResponse, other.platformTriggerGetResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            platformTriggerGetResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlatformTriggersGetResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "platformTriggerGetResponse", platformTriggerGetResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends PlatformTriggerGetResponse> platformTriggerGetResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Successful response.
         */
        public Builder platformTriggerGetResponse(PlatformTriggerGetResponse platformTriggerGetResponse) {
            Utils.checkNotNull(platformTriggerGetResponse, "platformTriggerGetResponse");
            this.platformTriggerGetResponse = Optional.ofNullable(platformTriggerGetResponse);
            return this;
        }

        /**
         * Successful response.
         */
        public Builder platformTriggerGetResponse(Optional<? extends PlatformTriggerGetResponse> platformTriggerGetResponse) {
            Utils.checkNotNull(platformTriggerGetResponse, "platformTriggerGetResponse");
            this.platformTriggerGetResponse = platformTriggerGetResponse;
            return this;
        }

        public PlatformTriggersGetResponse build() {

            return new PlatformTriggersGetResponse(
                contentType, statusCode, rawResponse,
                platformTriggerGetResponse);
        }

    }
}
