/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2b95913ef47b
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestlessOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.operations.PlatformAdminUsageSettingsGet;
import com.glean.api_client.glean_api_client.utils.Headers;
import java.util.concurrent.CompletableFuture;

public class PlatformAdminUsageSettingsGetRequestBuilder {

    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PlatformAdminUsageSettingsGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CompletableFuture<PlatformAdminUsageSettingsGetResponse> call() {
        
        AsyncRequestlessOperation<PlatformAdminUsageSettingsGetResponse> operation
            = new PlatformAdminUsageSettingsGet.Async(sdkConfiguration, _headers);

        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }
}
