/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.IndexEmployeeRequest;
import com.glean.api_client.glean_api_client.operations.PostApiIndexV1Indexemployee;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.util.concurrent.CompletableFuture;

public class PostApiIndexV1IndexemployeeRequestBuilder {

    private IndexEmployeeRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PostApiIndexV1IndexemployeeRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PostApiIndexV1IndexemployeeRequestBuilder request(IndexEmployeeRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<PostApiIndexV1IndexemployeeResponse> call() {
        
        AsyncRequestOperation<IndexEmployeeRequest, PostApiIndexV1IndexemployeeResponse> operation
              = new PostApiIndexV1Indexemployee.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
