/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.models.components.UpdateShortcutResponse;
import com.glean.api_client.glean_api_client.utils.AsyncResponse;
import com.glean.api_client.glean_api_client.utils.Blob;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class UpdateshortcutResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * OK
     */
    private Optional<? extends UpdateShortcutResponse> updateShortcutResponse;

    @JsonCreator
    public UpdateshortcutResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends UpdateShortcutResponse> updateShortcutResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(updateShortcutResponse, "updateShortcutResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.updateShortcutResponse = updateShortcutResponse;
    }
    
    public UpdateshortcutResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<UpdateShortcutResponse> updateShortcutResponse() {
        return (Optional<UpdateShortcutResponse>) updateShortcutResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public UpdateshortcutResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public UpdateshortcutResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public UpdateshortcutResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public UpdateshortcutResponse withUpdateShortcutResponse(UpdateShortcutResponse updateShortcutResponse) {
        Utils.checkNotNull(updateShortcutResponse, "updateShortcutResponse");
        this.updateShortcutResponse = Optional.ofNullable(updateShortcutResponse);
        return this;
    }


    /**
     * OK
     */
    public UpdateshortcutResponse withUpdateShortcutResponse(Optional<? extends UpdateShortcutResponse> updateShortcutResponse) {
        Utils.checkNotNull(updateShortcutResponse, "updateShortcutResponse");
        this.updateShortcutResponse = updateShortcutResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateshortcutResponse other = (UpdateshortcutResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.updateShortcutResponse, other.updateShortcutResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            updateShortcutResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateshortcutResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "updateShortcutResponse", updateShortcutResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends UpdateShortcutResponse> updateShortcutResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * OK
         */
        public Builder updateShortcutResponse(UpdateShortcutResponse updateShortcutResponse) {
            Utils.checkNotNull(updateShortcutResponse, "updateShortcutResponse");
            this.updateShortcutResponse = Optional.ofNullable(updateShortcutResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder updateShortcutResponse(Optional<? extends UpdateShortcutResponse> updateShortcutResponse) {
            Utils.checkNotNull(updateShortcutResponse, "updateShortcutResponse");
            this.updateShortcutResponse = updateShortcutResponse;
            return this;
        }

        public UpdateshortcutResponse build() {

            return new UpdateshortcutResponse(
                contentType, statusCode, rawResponse,
                updateShortcutResponse);
        }

    }
}
