/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.models.components.CreateAnnouncementRequest;
import com.glean.api_client.glean_api_client.models.components.DeleteAnnouncementRequest;
import com.glean.api_client.glean_api_client.models.components.UpdateAnnouncementRequest;
import com.glean.api_client.glean_api_client.models.operations.CreateannouncementRequest;
import com.glean.api_client.glean_api_client.models.operations.CreateannouncementRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.CreateannouncementResponse;
import com.glean.api_client.glean_api_client.models.operations.DeleteannouncementRequest;
import com.glean.api_client.glean_api_client.models.operations.DeleteannouncementRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.DeleteannouncementResponse;
import com.glean.api_client.glean_api_client.models.operations.UpdateannouncementRequest;
import com.glean.api_client.glean_api_client.models.operations.UpdateannouncementRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.UpdateannouncementResponse;
import com.glean.api_client.glean_api_client.operations.Createannouncement;
import com.glean.api_client.glean_api_client.operations.Deleteannouncement;
import com.glean.api_client.glean_api_client.operations.Updateannouncement;
import com.glean.api_client.glean_api_client.utils.Headers;
import java.lang.String;
import java.util.Optional;


public class Announcements {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncAnnouncements asyncSDK;

    Announcements(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncAnnouncements(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncAnnouncements async() {
        return asyncSDK;
    }

    /**
     * Create Announcement
     * 
     * <p>Create a textual announcement visible to some set of users based on department and location.
     * 
     * @return The call builder
     */
    public CreateannouncementRequestBuilder create() {
        return new CreateannouncementRequestBuilder(sdkConfiguration);
    }

    /**
     * Create Announcement
     * 
     * <p>Create a textual announcement visible to some set of users based on department and location.
     * 
     * @param createAnnouncementRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateannouncementResponse create(CreateAnnouncementRequest createAnnouncementRequest) {
        return create(Optional.empty(), createAnnouncementRequest);
    }

    /**
     * Create Announcement
     * 
     * <p>Create a textual announcement visible to some set of users based on department and location.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param createAnnouncementRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateannouncementResponse create(Optional<String> locale, CreateAnnouncementRequest createAnnouncementRequest) {
        CreateannouncementRequest request =
            CreateannouncementRequest
                .builder()
                .locale(locale)
                .createAnnouncementRequest(createAnnouncementRequest)
                .build();
        RequestOperation<CreateannouncementRequest, CreateannouncementResponse> operation
              = new Createannouncement.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete Announcement
     * 
     * <p>Delete an existing user-generated announcement.
     * 
     * @return The call builder
     */
    public DeleteannouncementRequestBuilder delete() {
        return new DeleteannouncementRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete Announcement
     * 
     * <p>Delete an existing user-generated announcement.
     * 
     * @param deleteAnnouncementRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteannouncementResponse delete(DeleteAnnouncementRequest deleteAnnouncementRequest) {
        return delete(Optional.empty(), deleteAnnouncementRequest);
    }

    /**
     * Delete Announcement
     * 
     * <p>Delete an existing user-generated announcement.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param deleteAnnouncementRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteannouncementResponse delete(Optional<String> locale, DeleteAnnouncementRequest deleteAnnouncementRequest) {
        DeleteannouncementRequest request =
            DeleteannouncementRequest
                .builder()
                .locale(locale)
                .deleteAnnouncementRequest(deleteAnnouncementRequest)
                .build();
        RequestOperation<DeleteannouncementRequest, DeleteannouncementResponse> operation
              = new Deleteannouncement.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update Announcement
     * 
     * <p>Update a textual announcement visible to some set of users based on department and location.
     * 
     * @return The call builder
     */
    public UpdateannouncementRequestBuilder update() {
        return new UpdateannouncementRequestBuilder(sdkConfiguration);
    }

    /**
     * Update Announcement
     * 
     * <p>Update a textual announcement visible to some set of users based on department and location.
     * 
     * @param updateAnnouncementRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateannouncementResponse update(UpdateAnnouncementRequest updateAnnouncementRequest) {
        return update(Optional.empty(), updateAnnouncementRequest);
    }

    /**
     * Update Announcement
     * 
     * <p>Update a textual announcement visible to some set of users based on department and location.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param updateAnnouncementRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateannouncementResponse update(Optional<String> locale, UpdateAnnouncementRequest updateAnnouncementRequest) {
        UpdateannouncementRequest request =
            UpdateannouncementRequest
                .builder()
                .locale(locale)
                .updateAnnouncementRequest(updateAnnouncementRequest)
                .build();
        RequestOperation<UpdateannouncementRequest, UpdateannouncementResponse> operation
              = new Updateannouncement.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
