/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 41f5be2f8342
 */
package com.glean.api_client.glean_api_client;

import com.glean.api_client.glean_api_client.utils.Headers;

/**
 * Glean API: # Introduction
 * In addition to the data sources that Glean has built-in support for, Glean also provides a REST API
 * that enables customers to put arbitrary content in the search index. This is useful, for example,
 * for doing permissions-aware search over content in internal tools that reside on-prem as well as for
 * searching over applications that Glean does not currently support first class. In addition these
 * APIs allow the customer to push organization data (people info, organization structure etc) into
 * Glean.
 * 
 * <p># Usage guidelines
 * This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible
 * changes along
 * with a 6-month sunset period for anything that requires developers to adopt the new versions.
 * 
 * <p># API Clients
 * Official API clients for the Glean Indexing API are available in multiple languages:
 * 
 * <p>- [Python](https://github.com/gleanwork/api-client-python)
 * - [TypeScript](https://github.com/gleanwork/api-client-typescript)
 * - [Go](https://github.com/gleanwork/api-client-go)
 * - [Java](https://github.com/gleanwork/api-client-java)
 * 
 * <p>These API clients provide type-safe, idiomatic interfaces for working with Glean IndexingAPIs in
 * your language of choice.
 */
public class AsyncGlean {
    private static final Headers _headers = Headers.EMPTY;

    private final AsyncAgents agents;

    private final AsyncSearch search;

    private final AsyncClient client;

    private final AsyncIndexing indexing;

    public AsyncAgents agents() {
        return agents;
    }

    public AsyncSearch search() {
        return search;
    }

    public AsyncClient client() {
        return client;
    }

    public AsyncIndexing indexing() {
        return indexing;
    }

    private final SDKConfiguration sdkConfiguration;
    private final Glean syncSDK;

    AsyncGlean(Glean syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.agents = new AsyncAgents(syncSDK.agents(), sdkConfiguration);
        this.search = new AsyncSearch(syncSDK.search(), sdkConfiguration);
        this.client = new AsyncClient(syncSDK.client(), sdkConfiguration);
        this.indexing = new AsyncIndexing(syncSDK.indexing(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Glean sync() {
        return syncSDK;
    }
}
