/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 64a2a6f928f7
 */
package com.glean.api_client.glean_api_client;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.models.components.PlatformChatCreateRequest;
import com.glean.api_client.glean_api_client.models.operations.async.PlatformChatCreateRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.async.PlatformChatCreateResponse;
import com.glean.api_client.glean_api_client.operations.PlatformChatCreate;
import com.glean.api_client.glean_api_client.utils.Headers;
import java.util.concurrent.CompletableFuture;


public class AsyncChat {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Chat syncSDK;

    AsyncChat(Chat syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Chat sync() {
        return syncSDK;
    }


    /**
     * Create a chat response
     * 
     * <p>Run an assistant turn. Set `stream` to true to receive server-sent events; otherwise the response is
     * a typed JSON response object.
     * 
     * @return The async call builder
     */
    public PlatformChatCreateRequestBuilder create() {
        return new PlatformChatCreateRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a chat response
     * 
     * <p>Run an assistant turn. Set `stream` to true to receive server-sent events; otherwise the response is
     * a typed JSON response object.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<PlatformChatCreateResponse>} - The async response
     */
    public CompletableFuture<PlatformChatCreateResponse> create(PlatformChatCreateRequest request) {
        AsyncRequestOperation<PlatformChatCreateRequest, PlatformChatCreateResponse> operation
              = new PlatformChatCreate.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
