/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bc11b718d590
 */
package com.glean.api_client.glean_api_client;

import static com.glean.api_client.glean_api_client.operations.Operations.AsyncRequestOperation;

import com.glean.api_client.glean_api_client.models.components.EditPinRequest;
import com.glean.api_client.glean_api_client.models.components.GetPinRequest;
import com.glean.api_client.glean_api_client.models.components.PinRequest;
import com.glean.api_client.glean_api_client.models.components.Unpin;
import com.glean.api_client.glean_api_client.models.operations.EditpinRequest;
import com.glean.api_client.glean_api_client.models.operations.GetpinRequest;
import com.glean.api_client.glean_api_client.models.operations.ListpinsRequest;
import com.glean.api_client.glean_api_client.models.operations.ListpinsRequestBody;
import com.glean.api_client.glean_api_client.models.operations.UnpinRequest;
import com.glean.api_client.glean_api_client.models.operations.async.EditpinRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.async.EditpinResponse;
import com.glean.api_client.glean_api_client.models.operations.async.GetpinRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.async.GetpinResponse;
import com.glean.api_client.glean_api_client.models.operations.async.ListpinsRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.async.ListpinsResponse;
import com.glean.api_client.glean_api_client.models.operations.async.PinRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.async.PinResponse;
import com.glean.api_client.glean_api_client.models.operations.async.UnpinRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.async.UnpinResponse;
import com.glean.api_client.glean_api_client.operations.Editpin;
import com.glean.api_client.glean_api_client.operations.Getpin;
import com.glean.api_client.glean_api_client.operations.Listpins;
import com.glean.api_client.glean_api_client.operations.Pin;
import com.glean.api_client.glean_api_client.utils.Headers;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncPins {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Pins syncSDK;

    AsyncPins(Pins syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Pins sync() {
        return syncSDK;
    }


    /**
     * Update pin
     * 
     * <p>Update an existing user-generated pin.
     * 
     * @return The async call builder
     */
    public EditpinRequestBuilder update() {
        return new EditpinRequestBuilder(sdkConfiguration);
    }

    /**
     * Update pin
     * 
     * <p>Update an existing user-generated pin.
     * 
     * @param editPinRequest 
     * @return {@code CompletableFuture<EditpinResponse>} - The async response
     */
    public CompletableFuture<EditpinResponse> update(EditPinRequest editPinRequest) {
        return update(Optional.empty(), editPinRequest);
    }

    /**
     * Update pin
     * 
     * <p>Update an existing user-generated pin.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param editPinRequest 
     * @return {@code CompletableFuture<EditpinResponse>} - The async response
     */
    public CompletableFuture<EditpinResponse> update(Optional<String> locale, EditPinRequest editPinRequest) {
        EditpinRequest request =
            EditpinRequest
                .builder()
                .locale(locale)
                .editPinRequest(editPinRequest)
                .build();
        AsyncRequestOperation<EditpinRequest, EditpinResponse> operation
              = new Editpin.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Read pin
     * 
     * <p>Read pin details given its ID.
     * 
     * @return The async call builder
     */
    public GetpinRequestBuilder retrieve() {
        return new GetpinRequestBuilder(sdkConfiguration);
    }

    /**
     * Read pin
     * 
     * <p>Read pin details given its ID.
     * 
     * @param getPinRequest 
     * @return {@code CompletableFuture<GetpinResponse>} - The async response
     */
    public CompletableFuture<GetpinResponse> retrieve(GetPinRequest getPinRequest) {
        return retrieve(Optional.empty(), getPinRequest);
    }

    /**
     * Read pin
     * 
     * <p>Read pin details given its ID.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param getPinRequest 
     * @return {@code CompletableFuture<GetpinResponse>} - The async response
     */
    public CompletableFuture<GetpinResponse> retrieve(Optional<String> locale, GetPinRequest getPinRequest) {
        GetpinRequest request =
            GetpinRequest
                .builder()
                .locale(locale)
                .getPinRequest(getPinRequest)
                .build();
        AsyncRequestOperation<GetpinRequest, GetpinResponse> operation
              = new Getpin.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * List pins
     * 
     * <p>Lists all pins.
     * 
     * @return The async call builder
     */
    public ListpinsRequestBuilder list() {
        return new ListpinsRequestBuilder(sdkConfiguration);
    }

    /**
     * List pins
     * 
     * <p>Lists all pins.
     * 
     * @param requestBody List pins request
     * @return {@code CompletableFuture<ListpinsResponse>} - The async response
     */
    public CompletableFuture<ListpinsResponse> list(ListpinsRequestBody requestBody) {
        return list(Optional.empty(), requestBody);
    }

    /**
     * List pins
     * 
     * <p>Lists all pins.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param requestBody List pins request
     * @return {@code CompletableFuture<ListpinsResponse>} - The async response
     */
    public CompletableFuture<ListpinsResponse> list(Optional<String> locale, ListpinsRequestBody requestBody) {
        ListpinsRequest request =
            ListpinsRequest
                .builder()
                .locale(locale)
                .requestBody(requestBody)
                .build();
        AsyncRequestOperation<ListpinsRequest, ListpinsResponse> operation
              = new Listpins.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Create pin
     * 
     * <p>Pin a document as a result for a given search query.Pin results that are known to be a good match.
     * 
     * @return The async call builder
     */
    public PinRequestBuilder create() {
        return new PinRequestBuilder(sdkConfiguration);
    }

    /**
     * Create pin
     * 
     * <p>Pin a document as a result for a given search query.Pin results that are known to be a good match.
     * 
     * @param pinRequest 
     * @return {@code CompletableFuture<PinResponse>} - The async response
     */
    public CompletableFuture<PinResponse> create(PinRequest pinRequest) {
        return create(Optional.empty(), pinRequest);
    }

    /**
     * Create pin
     * 
     * <p>Pin a document as a result for a given search query.Pin results that are known to be a good match.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param pinRequest 
     * @return {@code CompletableFuture<PinResponse>} - The async response
     */
    public CompletableFuture<PinResponse> create(Optional<String> locale, PinRequest pinRequest) {
        com.glean.api_client.glean_api_client.models.operations.PinRequest request =
            com.glean.api_client.glean_api_client.models.operations.PinRequest
                .builder()
                .locale(locale)
                .pinRequest(pinRequest)
                .build();
        AsyncRequestOperation<com.glean.api_client.glean_api_client.models.operations.PinRequest, PinResponse> operation
              = new Pin.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete pin
     * 
     * <p>Unpin a previously pinned result.
     * 
     * @return The async call builder
     */
    public UnpinRequestBuilder remove() {
        return new UnpinRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete pin
     * 
     * <p>Unpin a previously pinned result.
     * 
     * @param unpin 
     * @return {@code CompletableFuture<UnpinResponse>} - The async response
     */
    public CompletableFuture<UnpinResponse> remove(Unpin unpin) {
        return remove(Optional.empty(), unpin);
    }

    /**
     * Delete pin
     * 
     * <p>Unpin a previously pinned result.
     * 
     * @param locale The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
     * @param unpin 
     * @return {@code CompletableFuture<UnpinResponse>} - The async response
     */
    public CompletableFuture<UnpinResponse> remove(Optional<String> locale, Unpin unpin) {
        UnpinRequest request =
            UnpinRequest
                .builder()
                .locale(locale)
                .unpin(unpin)
                .build();
        AsyncRequestOperation<UnpinRequest, UnpinResponse> operation
              = new com.glean.api_client.glean_api_client.operations.Unpin.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
