/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f22d94b920b5
 */
package com.glean.api_client.glean_api_client;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.models.components.PlatformSearchRequest;
import com.glean.api_client.glean_api_client.models.operations.PlatformSearchRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.PlatformSearchResponse;
import com.glean.api_client.glean_api_client.operations.PlatformSearch;
import com.glean.api_client.glean_api_client.utils.Headers;


public class Search {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSearch asyncSDK;

    Search(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSearch(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSearch async() {
        return asyncSDK;
    }

    /**
     * Search
     * 
     * <p>Execute a search query and retrieve ranked results. This is the data retrieval variant of the search
     * API and returns only results and pagination state.
     * 
     * @return The call builder
     */
    public PlatformSearchRequestBuilder query() {
        return new PlatformSearchRequestBuilder(sdkConfiguration);
    }

    /**
     * Search
     * 
     * <p>Execute a search query and retrieve ranked results. This is the data retrieval variant of the search
     * API and returns only results and pagination state.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PlatformSearchResponse query(PlatformSearchRequest request) {
        RequestOperation<PlatformSearchRequest, PlatformSearchResponse> operation
              = new PlatformSearch.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
