/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bb072637f39b
 */
package com.glean.api_client.glean_api_client;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.models.components.AuthorizeActionPackRequest;
import com.glean.api_client.glean_api_client.models.components.AuthorizeToolServerRequest;
import com.glean.api_client.glean_api_client.models.components.ToolsCallRequest;
import com.glean.api_client.glean_api_client.models.operations.AuthorizeActionPackRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.AuthorizeActionPackResponse;
import com.glean.api_client.glean_api_client.models.operations.AuthorizeToolServerRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.AuthorizeToolServerResponse;
import com.glean.api_client.glean_api_client.models.operations.GetActionPackAuthStatusRequest;
import com.glean.api_client.glean_api_client.models.operations.GetActionPackAuthStatusRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.GetActionPackAuthStatusResponse;
import com.glean.api_client.glean_api_client.models.operations.GetRestApiV1ToolsListRequest;
import com.glean.api_client.glean_api_client.models.operations.GetRestApiV1ToolsListRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.GetRestApiV1ToolsListResponse;
import com.glean.api_client.glean_api_client.models.operations.GetToolServerAuthStatusRequest;
import com.glean.api_client.glean_api_client.models.operations.GetToolServerAuthStatusRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.GetToolServerAuthStatusResponse;
import com.glean.api_client.glean_api_client.models.operations.GetToolServerToolsRequest;
import com.glean.api_client.glean_api_client.models.operations.GetToolServerToolsRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.GetToolServerToolsResponse;
import com.glean.api_client.glean_api_client.models.operations.PostRestApiV1ToolsCallRequestBuilder;
import com.glean.api_client.glean_api_client.models.operations.PostRestApiV1ToolsCallResponse;
import com.glean.api_client.glean_api_client.operations.AuthorizeActionPack;
import com.glean.api_client.glean_api_client.operations.AuthorizeToolServer;
import com.glean.api_client.glean_api_client.operations.GetActionPackAuthStatus;
import com.glean.api_client.glean_api_client.operations.GetRestApiV1ToolsList;
import com.glean.api_client.glean_api_client.operations.GetToolServerAuthStatus;
import com.glean.api_client.glean_api_client.operations.GetToolServerTools;
import com.glean.api_client.glean_api_client.operations.PostRestApiV1ToolsCall;
import com.glean.api_client.glean_api_client.utils.Headers;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class Tools {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTools asyncSDK;

    Tools(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncTools(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTools async() {
        return asyncSDK;
    }

    /**
     * List available tools
     * 
     * <p>Returns a filtered set of available tools based on optional tool name parameters. If no filters are
     * provided, all available tools are returned.
     * 
     * @return The call builder
     */
    public GetRestApiV1ToolsListRequestBuilder list() {
        return new GetRestApiV1ToolsListRequestBuilder(sdkConfiguration);
    }

    /**
     * List available tools
     * 
     * <p>Returns a filtered set of available tools based on optional tool name parameters. If no filters are
     * provided, all available tools are returned.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetRestApiV1ToolsListResponse listDirect() {
        return list(Optional.empty());
    }

    /**
     * List available tools
     * 
     * <p>Returns a filtered set of available tools based on optional tool name parameters. If no filters are
     * provided, all available tools are returned.
     * 
     * @param toolNames Optional array of tool names to filter by
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetRestApiV1ToolsListResponse list(Optional<? extends List<String>> toolNames) {
        GetRestApiV1ToolsListRequest request =
            GetRestApiV1ToolsListRequest
                .builder()
                .toolNames(toolNames)
                .build();
        RequestOperation<GetRestApiV1ToolsListRequest, GetRestApiV1ToolsListResponse> operation
              = new GetRestApiV1ToolsList.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Execute the specified tool
     * 
     * <p>Execute the specified tool with provided parameters
     * 
     * @return The call builder
     */
    public PostRestApiV1ToolsCallRequestBuilder run() {
        return new PostRestApiV1ToolsCallRequestBuilder(sdkConfiguration);
    }

    /**
     * Execute the specified tool
     * 
     * <p>Execute the specified tool with provided parameters
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PostRestApiV1ToolsCallResponse run(ToolsCallRequest request) {
        RequestOperation<ToolsCallRequest, PostRestApiV1ToolsCallResponse> operation
              = new PostRestApiV1ToolsCall.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get end-user authentication status for an action pack.
     * 
     * <p>Reports whether the calling user is already authenticated against the third-party
     * tool backing the specified action pack. Intended for headless / server-driven clients
     * that render an "Authorize" prompt when the user has not yet consented to the tool.
     * 
     * @return The call builder
     */
    public GetActionPackAuthStatusRequestBuilder retrieveActionPackAuthStatus() {
        return new GetActionPackAuthStatusRequestBuilder(sdkConfiguration);
    }

    /**
     * Get end-user authentication status for an action pack.
     * 
     * <p>Reports whether the calling user is already authenticated against the third-party
     * tool backing the specified action pack. Intended for headless / server-driven clients
     * that render an "Authorize" prompt when the user has not yet consented to the tool.
     * 
     * @param actionPackId ID of the action pack to query or authorize.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetActionPackAuthStatusResponse retrieveActionPackAuthStatus(String actionPackId) {
        GetActionPackAuthStatusRequest request =
            GetActionPackAuthStatusRequest
                .builder()
                .actionPackId(actionPackId)
                .build();
        RequestOperation<GetActionPackAuthStatusRequest, GetActionPackAuthStatusResponse> operation
              = new GetActionPackAuthStatus.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Start the OAuth authorization flow for an action pack.
     * 
     * <p>Starts the third-party OAuth flow for the specified action pack and returns the
     * redirect URL that the client should navigate the end user to. After the OAuth
     * callback completes, the user's browser is redirected back to `returnUrl` with a
     * status query parameter (`?glean_action_auth=success|error&amp;actionPackId=...`).
     * 
     * <p>`returnUrl` must match the tenant's configured return URL allowlist; otherwise the
     * request is rejected with 400.
     * 
     * @return The call builder
     */
    public AuthorizeActionPackRequestBuilder authorizeActionPack() {
        return new AuthorizeActionPackRequestBuilder(sdkConfiguration);
    }

    /**
     * Start the OAuth authorization flow for an action pack.
     * 
     * <p>Starts the third-party OAuth flow for the specified action pack and returns the
     * redirect URL that the client should navigate the end user to. After the OAuth
     * callback completes, the user's browser is redirected back to `returnUrl` with a
     * status query parameter (`?glean_action_auth=success|error&amp;actionPackId=...`).
     * 
     * <p>`returnUrl` must match the tenant's configured return URL allowlist; otherwise the
     * request is rejected with 400.
     * 
     * @param actionPackId ID of the action pack to query or authorize.
     * @param authorizeActionPackRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AuthorizeActionPackResponse authorizeActionPack(String actionPackId, AuthorizeActionPackRequest authorizeActionPackRequest) {
        com.glean.api_client.glean_api_client.models.operations.AuthorizeActionPackRequest request =
            com.glean.api_client.glean_api_client.models.operations.AuthorizeActionPackRequest
                .builder()
                .actionPackId(actionPackId)
                .authorizeActionPackRequest(authorizeActionPackRequest)
                .build();
        RequestOperation<com.glean.api_client.glean_api_client.models.operations.AuthorizeActionPackRequest, AuthorizeActionPackResponse> operation
              = new AuthorizeActionPack.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get end-user authentication status for a tool server.
     * 
     * <p>Returns display information and the calling user's current authentication status
     * for the specified tool server.
     * 
     * @return The call builder
     */
    public GetToolServerAuthStatusRequestBuilder retrieveToolServerAuthStatus() {
        return new GetToolServerAuthStatusRequestBuilder(sdkConfiguration);
    }

    /**
     * Get end-user authentication status for a tool server.
     * 
     * <p>Returns display information and the calling user's current authentication status
     * for the specified tool server.
     * 
     * @param serverId Unique identifier of the tool server.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetToolServerAuthStatusResponse retrieveToolServerAuthStatus(String serverId) {
        GetToolServerAuthStatusRequest request =
            GetToolServerAuthStatusRequest
                .builder()
                .serverId(serverId)
                .build();
        RequestOperation<GetToolServerAuthStatusRequest, GetToolServerAuthStatusResponse> operation
              = new GetToolServerAuthStatus.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Start the OAuth authorization flow for a tool server.
     * 
     * <p>Initiates the third-party OAuth flow for the specified tool server and returns the
     * authorization URL that the client should navigate the end user to. After the OAuth
     * callback completes, the user's browser is redirected back to `returnUrl` with query
     * parameters indicating the result.
     * 
     * <p>`returnUrl` must match the tenant's configured return URL allowlist; otherwise the
     * request is rejected with 400.
     * 
     * @return The call builder
     */
    public AuthorizeToolServerRequestBuilder authorizeToolServer() {
        return new AuthorizeToolServerRequestBuilder(sdkConfiguration);
    }

    /**
     * Start the OAuth authorization flow for a tool server.
     * 
     * <p>Initiates the third-party OAuth flow for the specified tool server and returns the
     * authorization URL that the client should navigate the end user to. After the OAuth
     * callback completes, the user's browser is redirected back to `returnUrl` with query
     * parameters indicating the result.
     * 
     * <p>`returnUrl` must match the tenant's configured return URL allowlist; otherwise the
     * request is rejected with 400.
     * 
     * @param serverId Unique identifier of the tool server.
     * @param authorizeToolServerRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AuthorizeToolServerResponse authorizeToolServer(String serverId, AuthorizeToolServerRequest authorizeToolServerRequest) {
        com.glean.api_client.glean_api_client.models.operations.AuthorizeToolServerRequest request =
            com.glean.api_client.glean_api_client.models.operations.AuthorizeToolServerRequest
                .builder()
                .serverId(serverId)
                .authorizeToolServerRequest(authorizeToolServerRequest)
                .build();
        RequestOperation<com.glean.api_client.glean_api_client.models.operations.AuthorizeToolServerRequest, AuthorizeToolServerResponse> operation
              = new AuthorizeToolServer.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get tool definitions from a tool server.
     * 
     * <p>Returns the name, description and JSON input schema for the named tools on the
     * specified tool server. Works for both action packs and MCP servers.
     * 
     * <p>`toolNames` is required. Names that do not exist on the server are returned in
     * `notFound` rather than failing the request, so a single bad name does not force
     * callers into one-at-a-time retries. Matching is case-insensitive and treats `-`
     * and `_` as equivalent.
     * 
     * <p>Native tools are not served; `serverId=native` returns 404.
     * 
     * @return The call builder
     */
    public GetToolServerToolsRequestBuilder getToolServerTools() {
        return new GetToolServerToolsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get tool definitions from a tool server.
     * 
     * <p>Returns the name, description and JSON input schema for the named tools on the
     * specified tool server. Works for both action packs and MCP servers.
     * 
     * <p>`toolNames` is required. Names that do not exist on the server are returned in
     * `notFound` rather than failing the request, so a single bad name does not force
     * callers into one-at-a-time retries. Matching is case-insensitive and treats `-`
     * and `_` as equivalent.
     * 
     * <p>Native tools are not served; `serverId=native` returns 404.
     * 
     * @param serverId Unique identifier of the tool server.
     * @param toolNames Tool names to look up on this server. Maximum 100.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetToolServerToolsResponse getToolServerTools(String serverId, List<String> toolNames) {
        GetToolServerToolsRequest request =
            GetToolServerToolsRequest
                .builder()
                .serverId(serverId)
                .toolNames(toolNames)
                .build();
        RequestOperation<GetToolServerToolsRequest, GetToolServerToolsResponse> operation
              = new GetToolServerTools.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
