/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 39b51650b310
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class ChatCustomEntitySourceType {

    public static final ChatCustomEntitySourceType CUSTOM_ENTITY = new ChatCustomEntitySourceType("CUSTOM_ENTITY");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ChatCustomEntitySourceType> values = createValuesMap();
    private static final Map<String, ChatCustomEntitySourceTypeEnum> enums = createEnumsMap();

    private final String value;

    private ChatCustomEntitySourceType(String value) {
        this.value = value;
    }

    /**
     * Returns a ChatCustomEntitySourceType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ChatCustomEntitySourceType
     */ 
    @JsonCreator
    public static ChatCustomEntitySourceType of(String value) {
        synchronized (ChatCustomEntitySourceType.class) {
            return values.computeIfAbsent(value, v -> new ChatCustomEntitySourceType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ChatCustomEntitySourceTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ChatCustomEntitySourceType other = (ChatCustomEntitySourceType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ChatCustomEntitySourceType [value=" + value + "]";
    }

    // return an array just like an enum
    public static ChatCustomEntitySourceType[] values() {
        synchronized (ChatCustomEntitySourceType.class) {
            return values.values().toArray(new ChatCustomEntitySourceType[] {});
        }
    }

    private static final Map<String, ChatCustomEntitySourceType> createValuesMap() {
        Map<String, ChatCustomEntitySourceType> map = new LinkedHashMap<>();
        map.put("CUSTOM_ENTITY", CUSTOM_ENTITY);
        return map;
    }

    private static final Map<String, ChatCustomEntitySourceTypeEnum> createEnumsMap() {
        Map<String, ChatCustomEntitySourceTypeEnum> map = new HashMap<>();
        map.put("CUSTOM_ENTITY", ChatCustomEntitySourceTypeEnum.CUSTOM_ENTITY);
        return map;
    }
    
    
    public enum ChatCustomEntitySourceTypeEnum {

        CUSTOM_ENTITY("CUSTOM_ENTITY"),;

        private final String value;

        private ChatCustomEntitySourceTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

