/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b481265e6405
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class CollectionItemItemType {

    public static final CollectionItemItemType DOCUMENT = new CollectionItemItemType("DOCUMENT");
    public static final CollectionItemItemType TEXT = new CollectionItemItemType("TEXT");
    public static final CollectionItemItemType URL = new CollectionItemItemType("URL");
    public static final CollectionItemItemType COLLECTION = new CollectionItemItemType("COLLECTION");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, CollectionItemItemType> values = createValuesMap();
    private static final Map<String, CollectionItemItemTypeEnum> enums = createEnumsMap();

    private final String value;

    private CollectionItemItemType(String value) {
        this.value = value;
    }

    /**
     * Returns a CollectionItemItemType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as CollectionItemItemType
     */ 
    @JsonCreator
    public static CollectionItemItemType of(String value) {
        synchronized (CollectionItemItemType.class) {
            return values.computeIfAbsent(value, v -> new CollectionItemItemType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<CollectionItemItemTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CollectionItemItemType other = (CollectionItemItemType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "CollectionItemItemType [value=" + value + "]";
    }

    // return an array just like an enum
    public static CollectionItemItemType[] values() {
        synchronized (CollectionItemItemType.class) {
            return values.values().toArray(new CollectionItemItemType[] {});
        }
    }

    private static final Map<String, CollectionItemItemType> createValuesMap() {
        Map<String, CollectionItemItemType> map = new LinkedHashMap<>();
        map.put("DOCUMENT", DOCUMENT);
        map.put("TEXT", TEXT);
        map.put("URL", URL);
        map.put("COLLECTION", COLLECTION);
        return map;
    }

    private static final Map<String, CollectionItemItemTypeEnum> createEnumsMap() {
        Map<String, CollectionItemItemTypeEnum> map = new HashMap<>();
        map.put("DOCUMENT", CollectionItemItemTypeEnum.DOCUMENT);
        map.put("TEXT", CollectionItemItemTypeEnum.TEXT);
        map.put("URL", CollectionItemItemTypeEnum.URL);
        map.put("COLLECTION", CollectionItemItemTypeEnum.COLLECTION);
        return map;
    }
    
    
    public enum CollectionItemItemTypeEnum {

        DOCUMENT("DOCUMENT"),
        TEXT("TEXT"),
        URL("URL"),
        COLLECTION("COLLECTION"),;

        private final String value;

        private CollectionItemItemTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

