/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2253917ef6e7
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class CommunicationChannel {

    public static final CommunicationChannel COMMUNICATION_CHANNEL_EMAIL = new CommunicationChannel("COMMUNICATION_CHANNEL_EMAIL");
    public static final CommunicationChannel COMMUNICATION_CHANNEL_SLACK = new CommunicationChannel("COMMUNICATION_CHANNEL_SLACK");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, CommunicationChannel> values = createValuesMap();
    private static final Map<String, CommunicationChannelEnum> enums = createEnumsMap();

    private final String value;

    private CommunicationChannel(String value) {
        this.value = value;
    }

    /**
     * Returns a CommunicationChannel with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as CommunicationChannel
     */ 
    @JsonCreator
    public static CommunicationChannel of(String value) {
        synchronized (CommunicationChannel.class) {
            return values.computeIfAbsent(value, v -> new CommunicationChannel(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<CommunicationChannelEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CommunicationChannel other = (CommunicationChannel) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "CommunicationChannel [value=" + value + "]";
    }

    // return an array just like an enum
    public static CommunicationChannel[] values() {
        synchronized (CommunicationChannel.class) {
            return values.values().toArray(new CommunicationChannel[] {});
        }
    }

    private static final Map<String, CommunicationChannel> createValuesMap() {
        Map<String, CommunicationChannel> map = new LinkedHashMap<>();
        map.put("COMMUNICATION_CHANNEL_EMAIL", COMMUNICATION_CHANNEL_EMAIL);
        map.put("COMMUNICATION_CHANNEL_SLACK", COMMUNICATION_CHANNEL_SLACK);
        return map;
    }

    private static final Map<String, CommunicationChannelEnum> createEnumsMap() {
        Map<String, CommunicationChannelEnum> map = new HashMap<>();
        map.put("COMMUNICATION_CHANNEL_EMAIL", CommunicationChannelEnum.COMMUNICATION_CHANNEL_EMAIL);
        map.put("COMMUNICATION_CHANNEL_SLACK", CommunicationChannelEnum.COMMUNICATION_CHANNEL_SLACK);
        return map;
    }
    
    
    public enum CommunicationChannelEnum {

        COMMUNICATION_CHANNEL_EMAIL("COMMUNICATION_CHANNEL_EMAIL"),
        COMMUNICATION_CHANNEL_SLACK("COMMUNICATION_CHANNEL_SLACK"),;

        private final String value;

        private CommunicationChannelEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

