/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.glean.api_client.glean_api_client.utils.OneOfDeserializer;
import com.glean.api_client.glean_api_client.utils.TypedObject;
import com.glean.api_client.glean_api_client.utils.Utils.JsonShape;
import com.glean.api_client.glean_api_client.utils.Utils.TypeReferenceWithShape;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;

@JsonDeserialize(using = CustomFieldValue._Deserializer.class)
public class CustomFieldValue {

    @JsonValue
    private TypedObject value;
    
    private CustomFieldValue(TypedObject value) {
        this.value = value;
    }

    public static CustomFieldValue of(CustomFieldValueStr value) {
        Utils.checkNotNull(value, "value");
        return new CustomFieldValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<CustomFieldValueStr>(){}));
    }

    public static CustomFieldValue of(CustomFieldValueHyperlink value) {
        Utils.checkNotNull(value, "value");
        return new CustomFieldValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<CustomFieldValueHyperlink>(){}));
    }

    public static CustomFieldValue of(CustomFieldValuePerson value) {
        Utils.checkNotNull(value, "value");
        return new CustomFieldValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<CustomFieldValuePerson>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.glean.api_client.glean_api_client.models.components.CustomFieldValueStr}</li>
     * <li>{@code com.glean.api_client.glean_api_client.models.components.CustomFieldValueHyperlink}</li>
     * <li>{@code com.glean.api_client.glean_api_client.models.components.CustomFieldValuePerson}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomFieldValue other = (CustomFieldValue) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<CustomFieldValue> {

        public _Deserializer() {
            super(CustomFieldValue.class, false,
                  TypeReferenceWithShape.of(new TypeReference<CustomFieldValueHyperlink>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<CustomFieldValuePerson>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<CustomFieldValueStr>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(CustomFieldValue.class,
                "value", value);
    }
 
}

