/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9df8d4dc9a89
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GrantType
 * 
 * <p>The type of grant type being used.
 */
public class GrantType {

    public static final GrantType AUTH_CODE = new GrantType("AUTH_CODE");
    public static final GrantType CLIENT_CREDENTIALS = new GrantType("CLIENT_CREDENTIALS");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GrantType> values = createValuesMap();
    private static final Map<String, GrantTypeEnum> enums = createEnumsMap();

    private final String value;

    private GrantType(String value) {
        this.value = value;
    }

    /**
     * Returns a GrantType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GrantType
     */ 
    @JsonCreator
    public static GrantType of(String value) {
        synchronized (GrantType.class) {
            return values.computeIfAbsent(value, v -> new GrantType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GrantTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GrantType other = (GrantType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GrantType [value=" + value + "]";
    }

    // return an array just like an enum
    public static GrantType[] values() {
        synchronized (GrantType.class) {
            return values.values().toArray(new GrantType[] {});
        }
    }

    private static final Map<String, GrantType> createValuesMap() {
        Map<String, GrantType> map = new LinkedHashMap<>();
        map.put("AUTH_CODE", AUTH_CODE);
        map.put("CLIENT_CREDENTIALS", CLIENT_CREDENTIALS);
        return map;
    }

    private static final Map<String, GrantTypeEnum> createEnumsMap() {
        Map<String, GrantTypeEnum> map = new HashMap<>();
        map.put("AUTH_CODE", GrantTypeEnum.AUTH_CODE);
        map.put("CLIENT_CREDENTIALS", GrantTypeEnum.CLIENT_CREDENTIALS);
        return map;
    }
    
    
    public enum GrantTypeEnum {

        AUTH_CODE("AUTH_CODE"),
        CLIENT_CREDENTIALS("CLIENT_CREDENTIALS"),;

        private final String value;

        private GrantTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

