/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ea9908bd2500
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PersonToTeamRelationshipRelationship
 * 
 * <p>The team member's relationship to the team. This defaults to MEMBER if not set.
 */
public class PersonToTeamRelationshipRelationship {

    public static final PersonToTeamRelationshipRelationship MEMBER = new PersonToTeamRelationshipRelationship("MEMBER");
    public static final PersonToTeamRelationshipRelationship MANAGER = new PersonToTeamRelationshipRelationship("MANAGER");
    public static final PersonToTeamRelationshipRelationship LEAD = new PersonToTeamRelationshipRelationship("LEAD");
    public static final PersonToTeamRelationshipRelationship POINT_OF_CONTACT = new PersonToTeamRelationshipRelationship("POINT_OF_CONTACT");
    public static final PersonToTeamRelationshipRelationship OTHER = new PersonToTeamRelationshipRelationship("OTHER");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PersonToTeamRelationshipRelationship> values = createValuesMap();
    private static final Map<String, PersonToTeamRelationshipRelationshipEnum> enums = createEnumsMap();

    private final String value;

    private PersonToTeamRelationshipRelationship(String value) {
        this.value = value;
    }

    /**
     * Returns a PersonToTeamRelationshipRelationship with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PersonToTeamRelationshipRelationship
     */ 
    @JsonCreator
    public static PersonToTeamRelationshipRelationship of(String value) {
        synchronized (PersonToTeamRelationshipRelationship.class) {
            return values.computeIfAbsent(value, v -> new PersonToTeamRelationshipRelationship(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PersonToTeamRelationshipRelationshipEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PersonToTeamRelationshipRelationship other = (PersonToTeamRelationshipRelationship) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PersonToTeamRelationshipRelationship [value=" + value + "]";
    }

    // return an array just like an enum
    public static PersonToTeamRelationshipRelationship[] values() {
        synchronized (PersonToTeamRelationshipRelationship.class) {
            return values.values().toArray(new PersonToTeamRelationshipRelationship[] {});
        }
    }

    private static final Map<String, PersonToTeamRelationshipRelationship> createValuesMap() {
        Map<String, PersonToTeamRelationshipRelationship> map = new LinkedHashMap<>();
        map.put("MEMBER", MEMBER);
        map.put("MANAGER", MANAGER);
        map.put("LEAD", LEAD);
        map.put("POINT_OF_CONTACT", POINT_OF_CONTACT);
        map.put("OTHER", OTHER);
        return map;
    }

    private static final Map<String, PersonToTeamRelationshipRelationshipEnum> createEnumsMap() {
        Map<String, PersonToTeamRelationshipRelationshipEnum> map = new HashMap<>();
        map.put("MEMBER", PersonToTeamRelationshipRelationshipEnum.MEMBER);
        map.put("MANAGER", PersonToTeamRelationshipRelationshipEnum.MANAGER);
        map.put("LEAD", PersonToTeamRelationshipRelationshipEnum.LEAD);
        map.put("POINT_OF_CONTACT", PersonToTeamRelationshipRelationshipEnum.POINT_OF_CONTACT);
        map.put("OTHER", PersonToTeamRelationshipRelationshipEnum.OTHER);
        return map;
    }
    
    
    public enum PersonToTeamRelationshipRelationshipEnum {

        MEMBER("MEMBER"),
        MANAGER("MANAGER"),
        LEAD("LEAD"),
        POINT_OF_CONTACT("POINT_OF_CONTACT"),
        OTHER("OTHER"),;

        private final String value;

        private PersonToTeamRelationshipRelationshipEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

