/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 37ee631beae4
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class PlatformTriggerListResponse {
    /**
     * Triggers owned by the caller.
     */
    @JsonProperty("results")
    private List<PlatformTrigger> results;

    /**
     * Whether additional results are available.
     */
    @JsonProperty("has_more")
    private boolean hasMore;

    /**
     * Cursor for the next page, or null when no more results are available.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("next_cursor")
    private Optional<String> nextCursor;

    /**
     * Platform-generated request ID for support correlation.
     */
    @JsonProperty("request_id")
    private String requestId;

    @JsonCreator
    public PlatformTriggerListResponse(
            @JsonProperty("results") List<PlatformTrigger> results,
            @JsonProperty("has_more") boolean hasMore,
            @JsonProperty("next_cursor") Optional<String> nextCursor,
            @JsonProperty("request_id") String requestId) {
        Utils.checkNotNull(results, "results");
        Utils.checkNotNull(hasMore, "hasMore");
        Utils.checkNotNull(nextCursor, "nextCursor");
        Utils.checkNotNull(requestId, "requestId");
        this.results = results;
        this.hasMore = hasMore;
        this.nextCursor = nextCursor;
        this.requestId = requestId;
    }
    
    public PlatformTriggerListResponse(
            List<PlatformTrigger> results,
            boolean hasMore,
            String requestId) {
        this(results, hasMore, Optional.empty(),
            requestId);
    }

    /**
     * Triggers owned by the caller.
     */
    @JsonIgnore
    public List<PlatformTrigger> results() {
        return results;
    }

    /**
     * Whether additional results are available.
     */
    @JsonIgnore
    public boolean hasMore() {
        return hasMore;
    }

    /**
     * Cursor for the next page, or null when no more results are available.
     */
    @JsonIgnore
    public Optional<String> nextCursor() {
        return nextCursor;
    }

    /**
     * Platform-generated request ID for support correlation.
     */
    @JsonIgnore
    public String requestId() {
        return requestId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Triggers owned by the caller.
     */
    public PlatformTriggerListResponse withResults(List<PlatformTrigger> results) {
        Utils.checkNotNull(results, "results");
        this.results = results;
        return this;
    }

    /**
     * Whether additional results are available.
     */
    public PlatformTriggerListResponse withHasMore(boolean hasMore) {
        Utils.checkNotNull(hasMore, "hasMore");
        this.hasMore = hasMore;
        return this;
    }

    /**
     * Cursor for the next page, or null when no more results are available.
     */
    public PlatformTriggerListResponse withNextCursor(String nextCursor) {
        Utils.checkNotNull(nextCursor, "nextCursor");
        this.nextCursor = Optional.ofNullable(nextCursor);
        return this;
    }


    /**
     * Cursor for the next page, or null when no more results are available.
     */
    public PlatformTriggerListResponse withNextCursor(Optional<String> nextCursor) {
        Utils.checkNotNull(nextCursor, "nextCursor");
        this.nextCursor = nextCursor;
        return this;
    }

    /**
     * Platform-generated request ID for support correlation.
     */
    public PlatformTriggerListResponse withRequestId(String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlatformTriggerListResponse other = (PlatformTriggerListResponse) o;
        return 
            Utils.enhancedDeepEquals(this.results, other.results) &&
            Utils.enhancedDeepEquals(this.hasMore, other.hasMore) &&
            Utils.enhancedDeepEquals(this.nextCursor, other.nextCursor) &&
            Utils.enhancedDeepEquals(this.requestId, other.requestId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            results, hasMore, nextCursor,
            requestId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlatformTriggerListResponse.class,
                "results", results,
                "hasMore", hasMore,
                "nextCursor", nextCursor,
                "requestId", requestId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<PlatformTrigger> results;

        private Boolean hasMore;

        private Optional<String> nextCursor = Optional.empty();

        private String requestId;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Triggers owned by the caller.
         */
        public Builder results(List<PlatformTrigger> results) {
            Utils.checkNotNull(results, "results");
            this.results = results;
            return this;
        }


        /**
         * Whether additional results are available.
         */
        public Builder hasMore(boolean hasMore) {
            Utils.checkNotNull(hasMore, "hasMore");
            this.hasMore = hasMore;
            return this;
        }


        /**
         * Cursor for the next page, or null when no more results are available.
         */
        public Builder nextCursor(String nextCursor) {
            Utils.checkNotNull(nextCursor, "nextCursor");
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        /**
         * Cursor for the next page, or null when no more results are available.
         */
        public Builder nextCursor(Optional<String> nextCursor) {
            Utils.checkNotNull(nextCursor, "nextCursor");
            this.nextCursor = nextCursor;
            return this;
        }


        /**
         * Platform-generated request ID for support correlation.
         */
        public Builder requestId(String requestId) {
            Utils.checkNotNull(requestId, "requestId");
            this.requestId = requestId;
            return this;
        }

        public PlatformTriggerListResponse build() {

            return new PlatformTriggerListResponse(
                results, hasMore, nextCursor,
                requestId);
        }

    }
}
