/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c1cf5da6fc08
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;


public class PlatformMessage {
    /**
     * Role of the message author.
     */
    @JsonProperty("role")
    private PlatformMessageRole role;

    /**
     * Content blocks in the message.
     */
    @JsonProperty("content")
    private List<PlatformMessageTextBlock> content;

    @JsonCreator
    public PlatformMessage(
            @JsonProperty("role") PlatformMessageRole role,
            @JsonProperty("content") List<PlatformMessageTextBlock> content) {
        Utils.checkNotNull(role, "role");
        Utils.checkNotNull(content, "content");
        this.role = role;
        this.content = content;
    }

    /**
     * Role of the message author.
     */
    @JsonIgnore
    public PlatformMessageRole role() {
        return role;
    }

    /**
     * Content blocks in the message.
     */
    @JsonIgnore
    public List<PlatformMessageTextBlock> content() {
        return content;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Role of the message author.
     */
    public PlatformMessage withRole(PlatformMessageRole role) {
        Utils.checkNotNull(role, "role");
        this.role = role;
        return this;
    }

    /**
     * Content blocks in the message.
     */
    public PlatformMessage withContent(List<PlatformMessageTextBlock> content) {
        Utils.checkNotNull(content, "content");
        this.content = content;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlatformMessage other = (PlatformMessage) o;
        return 
            Utils.enhancedDeepEquals(this.role, other.role) &&
            Utils.enhancedDeepEquals(this.content, other.content);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            role, content);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlatformMessage.class,
                "role", role,
                "content", content);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PlatformMessageRole role;

        private List<PlatformMessageTextBlock> content;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Role of the message author.
         */
        public Builder role(PlatformMessageRole role) {
            Utils.checkNotNull(role, "role");
            this.role = role;
            return this;
        }


        /**
         * Content blocks in the message.
         */
        public Builder content(List<PlatformMessageTextBlock> content) {
            Utils.checkNotNull(content, "content");
            this.content = content;
            return this;
        }

        public PlatformMessage build() {

            return new PlatformMessage(
                role, content);
        }

    }
}
