/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d5a7815db26
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class PlatformChatFileSourceType {

    public static final PlatformChatFileSourceType FILE = new PlatformChatFileSourceType("file");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PlatformChatFileSourceType> values = createValuesMap();
    private static final Map<String, PlatformChatFileSourceTypeEnum> enums = createEnumsMap();

    private final String value;

    private PlatformChatFileSourceType(String value) {
        this.value = value;
    }

    /**
     * Returns a PlatformChatFileSourceType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PlatformChatFileSourceType
     */ 
    @JsonCreator
    public static PlatformChatFileSourceType of(String value) {
        synchronized (PlatformChatFileSourceType.class) {
            return values.computeIfAbsent(value, v -> new PlatformChatFileSourceType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PlatformChatFileSourceTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PlatformChatFileSourceType other = (PlatformChatFileSourceType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PlatformChatFileSourceType [value=" + value + "]";
    }

    // return an array just like an enum
    public static PlatformChatFileSourceType[] values() {
        synchronized (PlatformChatFileSourceType.class) {
            return values.values().toArray(new PlatformChatFileSourceType[] {});
        }
    }

    private static final Map<String, PlatformChatFileSourceType> createValuesMap() {
        Map<String, PlatformChatFileSourceType> map = new LinkedHashMap<>();
        map.put("file", FILE);
        return map;
    }

    private static final Map<String, PlatformChatFileSourceTypeEnum> createEnumsMap() {
        Map<String, PlatformChatFileSourceTypeEnum> map = new HashMap<>();
        map.put("file", PlatformChatFileSourceTypeEnum.FILE);
        return map;
    }
    
    
    public enum PlatformChatFileSourceTypeEnum {

        FILE("file"),;

        private final String value;

        private PlatformChatFileSourceTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

