/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 242984cf60aa
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.glean.api_client.glean_api_client.utils.LazySingletonValue;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * PlatformDepartmentFilter
 * 
 * <p>A filter on one department field.
 */
public class PlatformDepartmentFilter {
    /**
     * The department field to filter on. The only supported field is is_active.
     */
    @JsonProperty("field")
    private String field;

    /**
     * The values to match. A department matches when any value matches.
     */
    @JsonProperty("values")
    private List<String> values;

    /**
     * The only supported operator is EQUALS. Defaults to EQUALS.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("operator")
    private Optional<? extends PlatformDepartmentFilterOperator> operator;

    @JsonCreator
    public PlatformDepartmentFilter(
            @JsonProperty("field") String field,
            @JsonProperty("values") List<String> values,
            @JsonProperty("operator") Optional<? extends PlatformDepartmentFilterOperator> operator) {
        Utils.checkNotNull(field, "field");
        Utils.checkNotNull(values, "values");
        Utils.checkNotNull(operator, "operator");
        this.field = field;
        this.values = values;
        this.operator = operator;
    }
    
    public PlatformDepartmentFilter(
            String field,
            List<String> values) {
        this(field, values, Optional.empty());
    }

    /**
     * The department field to filter on. The only supported field is is_active.
     */
    @JsonIgnore
    public String field() {
        return field;
    }

    /**
     * The values to match. A department matches when any value matches.
     */
    @JsonIgnore
    public List<String> values() {
        return values;
    }

    /**
     * The only supported operator is EQUALS. Defaults to EQUALS.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PlatformDepartmentFilterOperator> operator() {
        return (Optional<PlatformDepartmentFilterOperator>) operator;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The department field to filter on. The only supported field is is_active.
     */
    public PlatformDepartmentFilter withField(String field) {
        Utils.checkNotNull(field, "field");
        this.field = field;
        return this;
    }

    /**
     * The values to match. A department matches when any value matches.
     */
    public PlatformDepartmentFilter withValues(List<String> values) {
        Utils.checkNotNull(values, "values");
        this.values = values;
        return this;
    }

    /**
     * The only supported operator is EQUALS. Defaults to EQUALS.
     */
    public PlatformDepartmentFilter withOperator(PlatformDepartmentFilterOperator operator) {
        Utils.checkNotNull(operator, "operator");
        this.operator = Optional.ofNullable(operator);
        return this;
    }


    /**
     * The only supported operator is EQUALS. Defaults to EQUALS.
     */
    public PlatformDepartmentFilter withOperator(Optional<? extends PlatformDepartmentFilterOperator> operator) {
        Utils.checkNotNull(operator, "operator");
        this.operator = operator;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlatformDepartmentFilter other = (PlatformDepartmentFilter) o;
        return 
            Utils.enhancedDeepEquals(this.field, other.field) &&
            Utils.enhancedDeepEquals(this.values, other.values) &&
            Utils.enhancedDeepEquals(this.operator, other.operator);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            field, values, operator);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlatformDepartmentFilter.class,
                "field", field,
                "values", values,
                "operator", operator);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String field;

        private List<String> values;

        private Optional<? extends PlatformDepartmentFilterOperator> operator;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The department field to filter on. The only supported field is is_active.
         */
        public Builder field(String field) {
            Utils.checkNotNull(field, "field");
            this.field = field;
            return this;
        }


        /**
         * The values to match. A department matches when any value matches.
         */
        public Builder values(List<String> values) {
            Utils.checkNotNull(values, "values");
            this.values = values;
            return this;
        }


        /**
         * The only supported operator is EQUALS. Defaults to EQUALS.
         */
        public Builder operator(PlatformDepartmentFilterOperator operator) {
            Utils.checkNotNull(operator, "operator");
            this.operator = Optional.ofNullable(operator);
            return this;
        }

        /**
         * The only supported operator is EQUALS. Defaults to EQUALS.
         */
        public Builder operator(Optional<? extends PlatformDepartmentFilterOperator> operator) {
            Utils.checkNotNull(operator, "operator");
            this.operator = operator;
            return this;
        }

        public PlatformDepartmentFilter build() {
            if (operator == null) {
                operator = _SINGLETON_VALUE_Operator.value();
            }

            return new PlatformDepartmentFilter(
                field, values, operator);
        }


        private static final LazySingletonValue<Optional<? extends PlatformDepartmentFilterOperator>> _SINGLETON_VALUE_Operator =
                new LazySingletonValue<>(
                        "operator",
                        "\"EQUALS\"",
                        new TypeReference<Optional<? extends PlatformDepartmentFilterOperator>>() {});
    }
}
