/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6e5ee1445d95
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class PlatformChatStreamProgressType {

    public static final PlatformChatStreamProgressType RESPONSE_PROGRESS = new PlatformChatStreamProgressType("RESPONSE_PROGRESS");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PlatformChatStreamProgressType> values = createValuesMap();
    private static final Map<String, PlatformChatStreamProgressTypeEnum> enums = createEnumsMap();

    private final String value;

    private PlatformChatStreamProgressType(String value) {
        this.value = value;
    }

    /**
     * Returns a PlatformChatStreamProgressType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PlatformChatStreamProgressType
     */ 
    @JsonCreator
    public static PlatformChatStreamProgressType of(String value) {
        synchronized (PlatformChatStreamProgressType.class) {
            return values.computeIfAbsent(value, v -> new PlatformChatStreamProgressType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PlatformChatStreamProgressTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PlatformChatStreamProgressType other = (PlatformChatStreamProgressType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PlatformChatStreamProgressType [value=" + value + "]";
    }

    // return an array just like an enum
    public static PlatformChatStreamProgressType[] values() {
        synchronized (PlatformChatStreamProgressType.class) {
            return values.values().toArray(new PlatformChatStreamProgressType[] {});
        }
    }

    private static final Map<String, PlatformChatStreamProgressType> createValuesMap() {
        Map<String, PlatformChatStreamProgressType> map = new LinkedHashMap<>();
        map.put("RESPONSE_PROGRESS", RESPONSE_PROGRESS);
        return map;
    }

    private static final Map<String, PlatformChatStreamProgressTypeEnum> createEnumsMap() {
        Map<String, PlatformChatStreamProgressTypeEnum> map = new HashMap<>();
        map.put("RESPONSE_PROGRESS", PlatformChatStreamProgressTypeEnum.RESPONSE_PROGRESS);
        return map;
    }
    
    
    public enum PlatformChatStreamProgressTypeEnum {

        RESPONSE_PROGRESS("RESPONSE_PROGRESS"),;

        private final String value;

        private PlatformChatStreamProgressTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

