/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 22ac0a98e4d4
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PropertyType
 * 
 * <p>The type of custom property - this governs the search and faceting behavior. Note that MULTIPICKLIST
 * is not yet supported.
 */
public class PropertyType {

    public static final PropertyType TEXT = new PropertyType("TEXT");
    public static final PropertyType DATE = new PropertyType("DATE");
    public static final PropertyType INT = new PropertyType("INT");
    public static final PropertyType USERID = new PropertyType("USERID");
    public static final PropertyType PICKLIST = new PropertyType("PICKLIST");
    public static final PropertyType TEXTLIST = new PropertyType("TEXTLIST");
    public static final PropertyType MULTIPICKLIST = new PropertyType("MULTIPICKLIST");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PropertyType> values = createValuesMap();
    private static final Map<String, PropertyTypeEnum> enums = createEnumsMap();

    private final String value;

    private PropertyType(String value) {
        this.value = value;
    }

    /**
     * Returns a PropertyType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PropertyType
     */ 
    @JsonCreator
    public static PropertyType of(String value) {
        synchronized (PropertyType.class) {
            return values.computeIfAbsent(value, v -> new PropertyType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PropertyTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PropertyType other = (PropertyType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PropertyType [value=" + value + "]";
    }

    // return an array just like an enum
    public static PropertyType[] values() {
        synchronized (PropertyType.class) {
            return values.values().toArray(new PropertyType[] {});
        }
    }

    private static final Map<String, PropertyType> createValuesMap() {
        Map<String, PropertyType> map = new LinkedHashMap<>();
        map.put("TEXT", TEXT);
        map.put("DATE", DATE);
        map.put("INT", INT);
        map.put("USERID", USERID);
        map.put("PICKLIST", PICKLIST);
        map.put("TEXTLIST", TEXTLIST);
        map.put("MULTIPICKLIST", MULTIPICKLIST);
        return map;
    }

    private static final Map<String, PropertyTypeEnum> createEnumsMap() {
        Map<String, PropertyTypeEnum> map = new HashMap<>();
        map.put("TEXT", PropertyTypeEnum.TEXT);
        map.put("DATE", PropertyTypeEnum.DATE);
        map.put("INT", PropertyTypeEnum.INT);
        map.put("USERID", PropertyTypeEnum.USERID);
        map.put("PICKLIST", PropertyTypeEnum.PICKLIST);
        map.put("TEXTLIST", PropertyTypeEnum.TEXTLIST);
        map.put("MULTIPICKLIST", PropertyTypeEnum.MULTIPICKLIST);
        return map;
    }
    
    
    public enum PropertyTypeEnum {

        TEXT("TEXT"),
        DATE("DATE"),
        INT("INT"),
        USERID("USERID"),
        PICKLIST("PICKLIST"),
        TEXTLIST("TEXTLIST"),
        MULTIPICKLIST("MULTIPICKLIST"),;

        private final String value;

        private PropertyTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

