/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7efb30396b18
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * ScopeType
 * 
 * <p>Describes the scope for a ReadPermission, WritePermission, or GrantPermission object
 */
public class ScopeType {

    public static final ScopeType GLOBAL = new ScopeType("GLOBAL");
    public static final ScopeType OWN = new ScopeType("OWN");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ScopeType> values = createValuesMap();
    private static final Map<String, ScopeTypeEnum> enums = createEnumsMap();

    private final String value;

    private ScopeType(String value) {
        this.value = value;
    }

    /**
     * Returns a ScopeType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ScopeType
     */ 
    @JsonCreator
    public static ScopeType of(String value) {
        synchronized (ScopeType.class) {
            return values.computeIfAbsent(value, v -> new ScopeType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ScopeTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ScopeType other = (ScopeType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ScopeType [value=" + value + "]";
    }

    // return an array just like an enum
    public static ScopeType[] values() {
        synchronized (ScopeType.class) {
            return values.values().toArray(new ScopeType[] {});
        }
    }

    private static final Map<String, ScopeType> createValuesMap() {
        Map<String, ScopeType> map = new LinkedHashMap<>();
        map.put("GLOBAL", GLOBAL);
        map.put("OWN", OWN);
        return map;
    }

    private static final Map<String, ScopeTypeEnum> createEnumsMap() {
        Map<String, ScopeTypeEnum> map = new HashMap<>();
        map.put("GLOBAL", ScopeTypeEnum.GLOBAL);
        map.put("OWN", ScopeTypeEnum.OWN);
        return map;
    }
    
    
    public enum ScopeTypeEnum {

        GLOBAL("GLOBAL"),
        OWN("OWN"),;

        private final String value;

        private ScopeTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

