/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a296643b32ae
 */
package com.glean.api_client.glean_api_client.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * TokenEndpointAuthMethod
 * 
 * <p>The OAuth 2.0 token endpoint authentication method (RFC 7591). Determines how the client
 * authenticates when exchanging an authorization code for a token. Values use lowercase to match the
 * OAuth 2.0 wire format (RFC 7591 Section 2).
 */
public class TokenEndpointAuthMethod {

    public static final TokenEndpointAuthMethod CLIENT_SECRET_POST = new TokenEndpointAuthMethod("client_secret_post");
    public static final TokenEndpointAuthMethod CLIENT_SECRET_BASIC = new TokenEndpointAuthMethod("client_secret_basic");
    public static final TokenEndpointAuthMethod NONE = new TokenEndpointAuthMethod("none");
    public static final TokenEndpointAuthMethod PRIVATE_KEY_JWT = new TokenEndpointAuthMethod("private_key_jwt");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, TokenEndpointAuthMethod> values = createValuesMap();
    private static final Map<String, TokenEndpointAuthMethodEnum> enums = createEnumsMap();

    private final String value;

    private TokenEndpointAuthMethod(String value) {
        this.value = value;
    }

    /**
     * Returns a TokenEndpointAuthMethod with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as TokenEndpointAuthMethod
     */ 
    @JsonCreator
    public static TokenEndpointAuthMethod of(String value) {
        synchronized (TokenEndpointAuthMethod.class) {
            return values.computeIfAbsent(value, v -> new TokenEndpointAuthMethod(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<TokenEndpointAuthMethodEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TokenEndpointAuthMethod other = (TokenEndpointAuthMethod) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "TokenEndpointAuthMethod [value=" + value + "]";
    }

    // return an array just like an enum
    public static TokenEndpointAuthMethod[] values() {
        synchronized (TokenEndpointAuthMethod.class) {
            return values.values().toArray(new TokenEndpointAuthMethod[] {});
        }
    }

    private static final Map<String, TokenEndpointAuthMethod> createValuesMap() {
        Map<String, TokenEndpointAuthMethod> map = new LinkedHashMap<>();
        map.put("client_secret_post", CLIENT_SECRET_POST);
        map.put("client_secret_basic", CLIENT_SECRET_BASIC);
        map.put("none", NONE);
        map.put("private_key_jwt", PRIVATE_KEY_JWT);
        return map;
    }

    private static final Map<String, TokenEndpointAuthMethodEnum> createEnumsMap() {
        Map<String, TokenEndpointAuthMethodEnum> map = new HashMap<>();
        map.put("client_secret_post", TokenEndpointAuthMethodEnum.CLIENT_SECRET_POST);
        map.put("client_secret_basic", TokenEndpointAuthMethodEnum.CLIENT_SECRET_BASIC);
        map.put("none", TokenEndpointAuthMethodEnum.NONE);
        map.put("private_key_jwt", TokenEndpointAuthMethodEnum.PRIVATE_KEY_JWT);
        return map;
    }
    
    
    public enum TokenEndpointAuthMethodEnum {

        CLIENT_SECRET_POST("client_secret_post"),
        CLIENT_SECRET_BASIC("client_secret_basic"),
        NONE("none"),
        PRIVATE_KEY_JWT("private_key_jwt"),;

        private final String value;

        private TokenEndpointAuthMethodEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

