workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Glean API:
        inputs:
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs
        output: .speakeasy/glean-merged-spec.yaml
targets:
    glean:
        target: java
        source: Glean API
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-java-code-samples
            labelOverride:
                fixedValue: Java (API Client)
            blocking: false
        testing:
            enabled: true
