/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 177d8e375f2b
 */
package com.glean.api_client.glean_api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.models.components.CreateWorkflowRequest;
import com.glean.api_client.glean_api_client.utils.SpeakeasyMetadata;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class CreateAgentRequest {
    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=locale")
    private Optional<String> locale;

    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours
     * behind UTC.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=timezoneOffset")
    private Optional<Long> timezoneOffset;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private CreateWorkflowRequest createWorkflowRequest;

    @JsonCreator
    public CreateAgentRequest(
            Optional<String> locale,
            Optional<Long> timezoneOffset,
            CreateWorkflowRequest createWorkflowRequest) {
        Utils.checkNotNull(locale, "locale");
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        Utils.checkNotNull(createWorkflowRequest, "createWorkflowRequest");
        this.locale = locale;
        this.timezoneOffset = timezoneOffset;
        this.createWorkflowRequest = createWorkflowRequest;
    }
    
    public CreateAgentRequest(
            CreateWorkflowRequest createWorkflowRequest) {
        this(Optional.empty(), Optional.empty(), createWorkflowRequest);
    }

    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    @JsonIgnore
    public Optional<String> locale() {
        return locale;
    }

    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours
     * behind UTC.
     */
    @JsonIgnore
    public Optional<Long> timezoneOffset() {
        return timezoneOffset;
    }

    @JsonIgnore
    public CreateWorkflowRequest createWorkflowRequest() {
        return createWorkflowRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    public CreateAgentRequest withLocale(String locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = Optional.ofNullable(locale);
        return this;
    }


    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    public CreateAgentRequest withLocale(Optional<String> locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = locale;
        return this;
    }

    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours
     * behind UTC.
     */
    public CreateAgentRequest withTimezoneOffset(long timezoneOffset) {
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        this.timezoneOffset = Optional.ofNullable(timezoneOffset);
        return this;
    }


    /**
     * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours
     * behind UTC.
     */
    public CreateAgentRequest withTimezoneOffset(Optional<Long> timezoneOffset) {
        Utils.checkNotNull(timezoneOffset, "timezoneOffset");
        this.timezoneOffset = timezoneOffset;
        return this;
    }

    public CreateAgentRequest withCreateWorkflowRequest(CreateWorkflowRequest createWorkflowRequest) {
        Utils.checkNotNull(createWorkflowRequest, "createWorkflowRequest");
        this.createWorkflowRequest = createWorkflowRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateAgentRequest other = (CreateAgentRequest) o;
        return 
            Utils.enhancedDeepEquals(this.locale, other.locale) &&
            Utils.enhancedDeepEquals(this.timezoneOffset, other.timezoneOffset) &&
            Utils.enhancedDeepEquals(this.createWorkflowRequest, other.createWorkflowRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            locale, timezoneOffset, createWorkflowRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateAgentRequest.class,
                "locale", locale,
                "timezoneOffset", timezoneOffset,
                "createWorkflowRequest", createWorkflowRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> locale = Optional.empty();

        private Optional<Long> timezoneOffset = Optional.empty();

        private CreateWorkflowRequest createWorkflowRequest;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
         * `Accept-Language` will be used.
         * 
         * <p>If not present or not supported, defaults to the closest match or `en`.
         */
        public Builder locale(String locale) {
            Utils.checkNotNull(locale, "locale");
            this.locale = Optional.ofNullable(locale);
            return this;
        }

        /**
         * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
         * `Accept-Language` will be used.
         * 
         * <p>If not present or not supported, defaults to the closest match or `en`.
         */
        public Builder locale(Optional<String> locale) {
            Utils.checkNotNull(locale, "locale");
            this.locale = locale;
            return this;
        }


        /**
         * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours
         * behind UTC.
         */
        public Builder timezoneOffset(long timezoneOffset) {
            Utils.checkNotNull(timezoneOffset, "timezoneOffset");
            this.timezoneOffset = Optional.ofNullable(timezoneOffset);
            return this;
        }

        /**
         * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours
         * behind UTC.
         */
        public Builder timezoneOffset(Optional<Long> timezoneOffset) {
            Utils.checkNotNull(timezoneOffset, "timezoneOffset");
            this.timezoneOffset = timezoneOffset;
            return this;
        }


        public Builder createWorkflowRequest(CreateWorkflowRequest createWorkflowRequest) {
            Utils.checkNotNull(createWorkflowRequest, "createWorkflowRequest");
            this.createWorkflowRequest = createWorkflowRequest;
            return this;
        }

        public CreateAgentRequest build() {

            return new CreateAgentRequest(
                locale, timezoneOffset, createWorkflowRequest);
        }

    }
}
