/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.models.components.DeleteAnswerRequest;
import com.glean.api_client.glean_api_client.utils.SpeakeasyMetadata;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DeleteanswerRequest {
    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=locale")
    private Optional<String> locale;

    /**
     * DeleteAnswer request
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private DeleteAnswerRequest deleteAnswerRequest;

    @JsonCreator
    public DeleteanswerRequest(
            Optional<String> locale,
            DeleteAnswerRequest deleteAnswerRequest) {
        Utils.checkNotNull(locale, "locale");
        Utils.checkNotNull(deleteAnswerRequest, "deleteAnswerRequest");
        this.locale = locale;
        this.deleteAnswerRequest = deleteAnswerRequest;
    }
    
    public DeleteanswerRequest(
            DeleteAnswerRequest deleteAnswerRequest) {
        this(Optional.empty(), deleteAnswerRequest);
    }

    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    @JsonIgnore
    public Optional<String> locale() {
        return locale;
    }

    /**
     * DeleteAnswer request
     */
    @JsonIgnore
    public DeleteAnswerRequest deleteAnswerRequest() {
        return deleteAnswerRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    public DeleteanswerRequest withLocale(String locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = Optional.ofNullable(locale);
        return this;
    }


    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    public DeleteanswerRequest withLocale(Optional<String> locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = locale;
        return this;
    }

    /**
     * DeleteAnswer request
     */
    public DeleteanswerRequest withDeleteAnswerRequest(DeleteAnswerRequest deleteAnswerRequest) {
        Utils.checkNotNull(deleteAnswerRequest, "deleteAnswerRequest");
        this.deleteAnswerRequest = deleteAnswerRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteanswerRequest other = (DeleteanswerRequest) o;
        return 
            Utils.enhancedDeepEquals(this.locale, other.locale) &&
            Utils.enhancedDeepEquals(this.deleteAnswerRequest, other.deleteAnswerRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            locale, deleteAnswerRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteanswerRequest.class,
                "locale", locale,
                "deleteAnswerRequest", deleteAnswerRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> locale = Optional.empty();

        private DeleteAnswerRequest deleteAnswerRequest;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
         * `Accept-Language` will be used.
         * 
         * <p>If not present or not supported, defaults to the closest match or `en`.
         */
        public Builder locale(String locale) {
            Utils.checkNotNull(locale, "locale");
            this.locale = Optional.ofNullable(locale);
            return this;
        }

        /**
         * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
         * `Accept-Language` will be used.
         * 
         * <p>If not present or not supported, defaults to the closest match or `en`.
         */
        public Builder locale(Optional<String> locale) {
            Utils.checkNotNull(locale, "locale");
            this.locale = locale;
            return this;
        }


        /**
         * DeleteAnswer request
         */
        public Builder deleteAnswerRequest(DeleteAnswerRequest deleteAnswerRequest) {
            Utils.checkNotNull(deleteAnswerRequest, "deleteAnswerRequest");
            this.deleteAnswerRequest = deleteAnswerRequest;
            return this;
        }

        public DeleteanswerRequest build() {

            return new DeleteanswerRequest(
                locale, deleteAnswerRequest);
        }

    }
}
