/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 453b9db47c6c
 */
package com.glean.api_client.glean_api_client.models.operations;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.operations.Deletefindingsexport;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Long;

public class DeletefindingsexportRequestBuilder {

    private Long id;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeletefindingsexportRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeletefindingsexportRequestBuilder id(long id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }


    private DeletefindingsexportRequest buildRequest() {

        DeletefindingsexportRequest request = new DeletefindingsexportRequest(id);

        return request;
    }

    public DeletefindingsexportResponse call() {
        
        RequestOperation<DeletefindingsexportRequest, DeletefindingsexportResponse> operation
              = new Deletefindingsexport.Sync(sdkConfiguration, _headers);
        DeletefindingsexportRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
