/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.GetCollectionRequest;
import com.glean.api_client.glean_api_client.operations.Getcollection;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;

public class GetcollectionRequestBuilder {

    private GetCollectionRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetcollectionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetcollectionRequestBuilder request(GetCollectionRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetcollectionResponse call() {
        
        RequestOperation<GetCollectionRequest, GetcollectionResponse> operation
              = new Getcollection.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
