/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.PeopleRequest;
import com.glean.api_client.glean_api_client.operations.PeopleOperation;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Exception;

public class PeopleRequestBuilder {

    private PeopleRequest request;
    private final SDKConfiguration sdkConfiguration;

    public PeopleRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PeopleRequestBuilder request(PeopleRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PeopleResponse call() throws Exception {
        
        RequestOperation<PeopleRequest, PeopleResponse> operation
              = new PeopleOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
