/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ca0b020636b0
 */
package com.glean.api_client.glean_api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.models.components.PlatformSkillUpdateRequest;
import com.glean.api_client.glean_api_client.utils.SpeakeasyMetadata;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class PlatformSkillsUpdateRequest {
    /**
     * Glean skill ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=skill_id")
    private String skillId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private PlatformSkillUpdateRequest platformSkillUpdateRequest;

    @JsonCreator
    public PlatformSkillsUpdateRequest(
            String skillId,
            PlatformSkillUpdateRequest platformSkillUpdateRequest) {
        Utils.checkNotNull(skillId, "skillId");
        Utils.checkNotNull(platformSkillUpdateRequest, "platformSkillUpdateRequest");
        this.skillId = skillId;
        this.platformSkillUpdateRequest = platformSkillUpdateRequest;
    }

    /**
     * Glean skill ID.
     */
    @JsonIgnore
    public String skillId() {
        return skillId;
    }

    @JsonIgnore
    public PlatformSkillUpdateRequest platformSkillUpdateRequest() {
        return platformSkillUpdateRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Glean skill ID.
     */
    public PlatformSkillsUpdateRequest withSkillId(String skillId) {
        Utils.checkNotNull(skillId, "skillId");
        this.skillId = skillId;
        return this;
    }

    public PlatformSkillsUpdateRequest withPlatformSkillUpdateRequest(PlatformSkillUpdateRequest platformSkillUpdateRequest) {
        Utils.checkNotNull(platformSkillUpdateRequest, "platformSkillUpdateRequest");
        this.platformSkillUpdateRequest = platformSkillUpdateRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlatformSkillsUpdateRequest other = (PlatformSkillsUpdateRequest) o;
        return 
            Utils.enhancedDeepEquals(this.skillId, other.skillId) &&
            Utils.enhancedDeepEquals(this.platformSkillUpdateRequest, other.platformSkillUpdateRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            skillId, platformSkillUpdateRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlatformSkillsUpdateRequest.class,
                "skillId", skillId,
                "platformSkillUpdateRequest", platformSkillUpdateRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String skillId;

        private PlatformSkillUpdateRequest platformSkillUpdateRequest;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Glean skill ID.
         */
        public Builder skillId(String skillId) {
            Utils.checkNotNull(skillId, "skillId");
            this.skillId = skillId;
            return this;
        }


        public Builder platformSkillUpdateRequest(PlatformSkillUpdateRequest platformSkillUpdateRequest) {
            Utils.checkNotNull(platformSkillUpdateRequest, "platformSkillUpdateRequest");
            this.platformSkillUpdateRequest = platformSkillUpdateRequest;
            return this;
        }

        public PlatformSkillsUpdateRequest build() {

            return new PlatformSkillsUpdateRequest(
                skillId, platformSkillUpdateRequest);
        }

    }
}
