/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 218173a41a84
 */
package com.glean.api_client.glean_api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.glean.api_client.glean_api_client.models.components.PlatformChatJsonSchemaFormat;
import com.glean.api_client.glean_api_client.models.components.PlatformChatTextFormat;
import com.glean.api_client.glean_api_client.utils.OneOfDeserializer;
import com.glean.api_client.glean_api_client.utils.TypedObject;
import com.glean.api_client.glean_api_client.utils.Utils.JsonShape;
import com.glean.api_client.glean_api_client.utils.Utils.TypeReferenceWithShape;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * PlatformChatCreateFormat
 * 
 * <p>Output format for the assistant text. TEXT is unconstrained. JSON_SCHEMA constrains the response to
 * the supplied schema.
 */
@JsonDeserialize(using = PlatformChatCreateFormat._Deserializer.class)
public class PlatformChatCreateFormat {

    @JsonValue
    private final TypedObject value;
    
    private PlatformChatCreateFormat(TypedObject value) {
        this.value = value;
    }

    public static PlatformChatCreateFormat of(PlatformChatTextFormat value) {
        Utils.checkNotNull(value, "value");
        return new PlatformChatCreateFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static PlatformChatCreateFormat of(PlatformChatJsonSchemaFormat value) {
        Utils.checkNotNull(value, "value");
        return new PlatformChatCreateFormat(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.glean.api_client.glean_api_client.models.components.PlatformChatTextFormat}</li>
     * <li>{@code com.glean.api_client.glean_api_client.models.components.PlatformChatJsonSchemaFormat}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlatformChatCreateFormat other = (PlatformChatCreateFormat) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<PlatformChatCreateFormat> {

        public _Deserializer() {
            super(PlatformChatCreateFormat.class, false,
                  TypeReferenceWithShape.of(new TypeReference<PlatformChatTextFormat>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<PlatformChatJsonSchemaFormat>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlatformChatCreateFormat.class,
                "value", value);
    }

}

