/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 466526c60e92
 */
package com.glean.api_client.glean_api_client.models.operations;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.operations.PlatformAdminUsageRequestsGet;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.String;

public class PlatformAdminUsageRequestsGetRequestBuilder {

    private String requestId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PlatformAdminUsageRequestsGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PlatformAdminUsageRequestsGetRequestBuilder requestId(String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
        return this;
    }


    private PlatformAdminUsageRequestsGetRequest buildRequest() {

        PlatformAdminUsageRequestsGetRequest request = new PlatformAdminUsageRequestsGetRequest(requestId);

        return request;
    }

    public PlatformAdminUsageRequestsGetResponse call() {
        
        RequestOperation<PlatformAdminUsageRequestsGetRequest, PlatformAdminUsageRequestsGetResponse> operation
              = new PlatformAdminUsageRequestsGet.Sync(sdkConfiguration, _headers);
        PlatformAdminUsageRequestsGetRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
