/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c784c11f038
 */
package com.glean.api_client.glean_api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.utils.SpeakeasyMetadata;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class PlatformSkillsListRequest {
    /**
     * Maximum number of skills to return.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
    private Optional<Long> pageSize;

    /**
     * Opaque pagination cursor from a previous response.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=cursor")
    private Optional<String> cursor;

    @JsonCreator
    public PlatformSkillsListRequest(
            Optional<Long> pageSize,
            Optional<String> cursor) {
        Utils.checkNotNull(pageSize, "pageSize");
        Utils.checkNotNull(cursor, "cursor");
        this.pageSize = pageSize;
        this.cursor = cursor;
    }
    
    public PlatformSkillsListRequest() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * Maximum number of skills to return.
     */
    @JsonIgnore
    public Optional<Long> pageSize() {
        return pageSize;
    }

    /**
     * Opaque pagination cursor from a previous response.
     */
    @JsonIgnore
    public Optional<String> cursor() {
        return cursor;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Maximum number of skills to return.
     */
    public PlatformSkillsListRequest withPageSize(long pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.ofNullable(pageSize);
        return this;
    }


    /**
     * Maximum number of skills to return.
     */
    public PlatformSkillsListRequest withPageSize(Optional<Long> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Opaque pagination cursor from a previous response.
     */
    public PlatformSkillsListRequest withCursor(String cursor) {
        Utils.checkNotNull(cursor, "cursor");
        this.cursor = Optional.ofNullable(cursor);
        return this;
    }


    /**
     * Opaque pagination cursor from a previous response.
     */
    public PlatformSkillsListRequest withCursor(Optional<String> cursor) {
        Utils.checkNotNull(cursor, "cursor");
        this.cursor = cursor;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlatformSkillsListRequest other = (PlatformSkillsListRequest) o;
        return 
            Utils.enhancedDeepEquals(this.pageSize, other.pageSize) &&
            Utils.enhancedDeepEquals(this.cursor, other.cursor);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            pageSize, cursor);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PlatformSkillsListRequest.class,
                "pageSize", pageSize,
                "cursor", cursor);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Long> pageSize = Optional.empty();

        private Optional<String> cursor = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Maximum number of skills to return.
         */
        public Builder pageSize(long pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        /**
         * Maximum number of skills to return.
         */
        public Builder pageSize(Optional<Long> pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = pageSize;
            return this;
        }


        /**
         * Opaque pagination cursor from a previous response.
         */
        public Builder cursor(String cursor) {
            Utils.checkNotNull(cursor, "cursor");
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        /**
         * Opaque pagination cursor from a previous response.
         */
        public Builder cursor(Optional<String> cursor) {
            Utils.checkNotNull(cursor, "cursor");
            this.cursor = cursor;
            return this;
        }

        public PlatformSkillsListRequest build() {

            return new PlatformSkillsListRequest(
                pageSize, cursor);
        }

    }
}
