/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 05f032f28ae9
 */
package com.glean.api_client.glean_api_client.models.operations;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.PlatformAgentRunResponsesRequest;
import com.glean.api_client.glean_api_client.operations.PlatformAgentsCreateRunResponses;
import com.glean.api_client.glean_api_client.utils.Headers;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.String;

public class PlatformAgentsCreateRunResponsesRequestBuilder {

    private String agentId;
    private PlatformAgentRunResponsesRequest platformAgentRunResponsesRequest;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PlatformAgentsCreateRunResponsesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PlatformAgentsCreateRunResponsesRequestBuilder agentId(String agentId) {
        Utils.checkNotNull(agentId, "agentId");
        this.agentId = agentId;
        return this;
    }

    public PlatformAgentsCreateRunResponsesRequestBuilder platformAgentRunResponsesRequest(PlatformAgentRunResponsesRequest platformAgentRunResponsesRequest) {
        Utils.checkNotNull(platformAgentRunResponsesRequest, "platformAgentRunResponsesRequest");
        this.platformAgentRunResponsesRequest = platformAgentRunResponsesRequest;
        return this;
    }


    private PlatformAgentsCreateRunResponsesRequest buildRequest() {

        PlatformAgentsCreateRunResponsesRequest request = new PlatformAgentsCreateRunResponsesRequest(agentId,
            platformAgentRunResponsesRequest);

        return request;
    }

    public PlatformAgentsCreateRunResponsesResponse call() {
        
        RequestOperation<PlatformAgentsCreateRunResponsesRequest, PlatformAgentsCreateRunResponsesResponse> operation
              = new PlatformAgentsCreateRunResponses.Sync(sdkConfiguration, _headers);
        PlatformAgentsCreateRunResponsesRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
