/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.glean_api_client.models.operations;

import static com.glean.api_client.glean_api_client.operations.Operations.RequestOperation;

import com.glean.api_client.glean_api_client.SDKConfiguration;
import com.glean.api_client.glean_api_client.models.components.UploadShortcutsRequest;
import com.glean.api_client.glean_api_client.operations.PostApiIndexV1UploadshortcutsOperation;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Exception;

public class PostApiIndexV1UploadshortcutsRequestBuilder {

    private UploadShortcutsRequest request;
    private final SDKConfiguration sdkConfiguration;

    public PostApiIndexV1UploadshortcutsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PostApiIndexV1UploadshortcutsRequestBuilder request(UploadShortcutsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PostApiIndexV1UploadshortcutsResponse call() throws Exception {
        
        RequestOperation<UploadShortcutsRequest, PostApiIndexV1UploadshortcutsResponse> operation
              = new PostApiIndexV1UploadshortcutsOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
