/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9ce034215b79
 */
package com.glean.api_client.glean_api_client.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.glean.api_client.glean_api_client.models.components.UpdateShortcutRequest;
import com.glean.api_client.glean_api_client.utils.SpeakeasyMetadata;
import com.glean.api_client.glean_api_client.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class UpdateshortcutRequest {
    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=locale")
    private Optional<String> locale;

    /**
     * Shortcut content. Id need to be specified for the shortcut.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private UpdateShortcutRequest updateShortcutRequest;

    @JsonCreator
    public UpdateshortcutRequest(
            Optional<String> locale,
            UpdateShortcutRequest updateShortcutRequest) {
        Utils.checkNotNull(locale, "locale");
        Utils.checkNotNull(updateShortcutRequest, "updateShortcutRequest");
        this.locale = locale;
        this.updateShortcutRequest = updateShortcutRequest;
    }
    
    public UpdateshortcutRequest(
            UpdateShortcutRequest updateShortcutRequest) {
        this(Optional.empty(), updateShortcutRequest);
    }

    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    @JsonIgnore
    public Optional<String> locale() {
        return locale;
    }

    /**
     * Shortcut content. Id need to be specified for the shortcut.
     */
    @JsonIgnore
    public UpdateShortcutRequest updateShortcutRequest() {
        return updateShortcutRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    public UpdateshortcutRequest withLocale(String locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = Optional.ofNullable(locale);
        return this;
    }


    /**
     * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
     * `Accept-Language` will be used.
     * 
     * <p>If not present or not supported, defaults to the closest match or `en`.
     */
    public UpdateshortcutRequest withLocale(Optional<String> locale) {
        Utils.checkNotNull(locale, "locale");
        this.locale = locale;
        return this;
    }

    /**
     * Shortcut content. Id need to be specified for the shortcut.
     */
    public UpdateshortcutRequest withUpdateShortcutRequest(UpdateShortcutRequest updateShortcutRequest) {
        Utils.checkNotNull(updateShortcutRequest, "updateShortcutRequest");
        this.updateShortcutRequest = updateShortcutRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateshortcutRequest other = (UpdateshortcutRequest) o;
        return 
            Utils.enhancedDeepEquals(this.locale, other.locale) &&
            Utils.enhancedDeepEquals(this.updateShortcutRequest, other.updateShortcutRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            locale, updateShortcutRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateshortcutRequest.class,
                "locale", locale,
                "updateShortcutRequest", updateShortcutRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> locale = Optional.empty();

        private UpdateShortcutRequest updateShortcutRequest;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
         * `Accept-Language` will be used.
         * 
         * <p>If not present or not supported, defaults to the closest match or `en`.
         */
        public Builder locale(String locale) {
            Utils.checkNotNull(locale, "locale");
            this.locale = Optional.ofNullable(locale);
            return this;
        }

        /**
         * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the
         * `Accept-Language` will be used.
         * 
         * <p>If not present or not supported, defaults to the closest match or `en`.
         */
        public Builder locale(Optional<String> locale) {
            Utils.checkNotNull(locale, "locale");
            this.locale = locale;
            return this;
        }


        /**
         * Shortcut content. Id need to be specified for the shortcut.
         */
        public Builder updateShortcutRequest(UpdateShortcutRequest updateShortcutRequest) {
            Utils.checkNotNull(updateShortcutRequest, "updateShortcutRequest");
            this.updateShortcutRequest = updateShortcutRequest;
            return this;
        }

        public UpdateshortcutRequest build() {

            return new UpdateshortcutRequest(
                locale, updateShortcutRequest);
        }

    }
}
