/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.glean.api_client.utils;

/**
 * Implemented by classes that have security annotations on fields.
 **/
public interface HasSecurity {
}